My Application: Missile Class Reference
Missile Class Reference
Defines Missile and its methods.
#include <Missile.h>
Public Member Functions
Missile ()
Missile Constructor.
Missile (const int &AmmoInMag)
Missile Copy Constructor.
~Missile ()
Missile destructor.
Vector3 getPositionOfMissile ()
Missile getPositionOfMissile function.
void updatePosition (const Vector3 &pos)
Missile updatePosition function.
void setView (const Vector3 &view)
Missile setView function.
void Animation (double dt)
Missile Animation function.
void init (Camera3 *target)
Camera3 initializer.
void Firing ()
Missile Firing function.
void update (double dt)
Missile update function.
Data Fields
Vector3 position
Vector3 missilePosition
int Missiles
int MissileUsed = 100
int delay = 0
Missile * Capacity
Private Attributes
Vector3 view
Camera3 * camera
Detailed Description
Defines Missile and its methods.
Class Missile:
Definition at line 23 of file Missile.h.
Constructor & Destructor Documentation
Missile::Missile ()
Missile Constructor.
Definition at line 17 of file Missile.cpp.
Missile::Missile (const int & AmmoInMag)
Missile Copy Constructor.
Parameters
const int reference AmmoInMag
Definition at line 28 of file Missile.cpp.
References Capacity, and Missiles.
Missile::~Missile ()
Missile destructor.
Definition at line 39 of file Missile.cpp.
Member Function Documentation
void Missile::Animation (double dt)
Missile Animation function.
Parameters
double dt
Definition at line 88 of file Missile.cpp.
References position, view, Vector3::x, Vector3::y, and Vector3::z.
Referenced by update().
void Missile::Firing ()
Missile Firing function.
Definition at line 115 of file Missile.cpp.
References camera, Capacity, Missiles, MissileUsed, setView(), Camera::target, updatePosition(), and Camera::view.
Referenced by SceneGalaxy::Update().
Vector3 Missile::getPositionOfMissile ()
Missile getPositionOfMissile function.
Returns
return position from update
Definition at line 64 of file Missile.cpp.
References position.
Referenced by SceneGalaxy::RenderMissile(), and update().
void Missile::init (Camera3 * target)
Camera3 initializer.
Parameters
Camera3 pointer
Definition at line 105 of file Missile.cpp.
References camera.
Referenced by SceneGalaxy::Init().
void Missile::setView (const Vector3 & view)
Missile setView function.
Parameters
const Vector3 reference view
Definition at line 76 of file Missile.cpp.
References view.
Referenced by Firing().
void Missile::update (double dt)
Missile update function.
Parameters
double dt
Definition at line 137 of file Missile.cpp.
References Animation(), Capacity, getPositionOfMissile(), and Missiles.
Referenced by SceneGalaxy::Update().
void Missile::updatePosition (const Vector3 & pos)
Missile updatePosition function.
Parameters
const Vector3 reference position
Definition at line 50 of file Missile.cpp.
References position, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Firing().
Field Documentation
Camera3* Missile::camera private
Definition at line 49 of file Missile.h.
Referenced by Firing(), and init().
Missile* Missile::Capacity
Definition at line 44 of file Missile.h.
Referenced by Firing(), Missile(), SceneGalaxy::RenderMissile(), and update().
int Missile::delay = 0
Definition at line 43 of file Missile.h.
Vector3 Missile::missilePosition
Definition at line 34 of file Missile.h.
int Missile::Missiles
Definition at line 41 of file Missile.h.
Referenced by Firing(), Missile(), SceneGalaxy::RenderMissile(), and update().
int Missile::MissileUsed = 100
Definition at line 42 of file Missile.h.
Referenced by Firing().
Vector3 Missile::position
Definition at line 33 of file Missile.h.
Referenced by Animation(), getPositionOfMissile(), and updatePosition().
Vector3 Missile::view private
Definition at line 48 of file Missile.h.
Referenced by Animation(), and setView().
The documentation for this class was generated from the following files:
LiZhaoyuan1/Source/Missile.h
LiZhaoyuan1/Source/Missile.cpp