My Application: SceneSoraJewel Class Reference
SceneSoraJewel Class Reference
Defines the scene Sora Jewel and its methods.
#include <SceneSoraJewel.h>
Public Member Functions
SceneSoraJewel ()
constructor for the .cpp file
~SceneSoraJewel ()
deconstructor for the .cpp file
void skybox ()
void renderLast ()
This function is placed in the Render() near the end so that we can avoid depth problems.
void renderText ()
This function renders the textbox and the chat.
void renderNPCAnimations ()
void interactions ()
This function is responsible for using view to do interaction instead of using an area.
virtual void Init ()
This function initialises everything needed for the scene.
virtual void Update (double dt)
This function is constantly running to update the scene such as animation and game logics.
virtual void Render ()
This function is the main and is responsible for getting the OBJ and or mesh to the sccene.
virtual void Exit ()
Clears whatever is done in init, render and update.
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_QUAD, GEO_LIGHTBALL, GEO_TEXT,
GEO_SORAJEWELLEFT, GEO_SORAJEWELRIGHT, GEO_SORAJEWELTOP, GEO_SORAJEWELBOTTOM,
GEO_SORAJEWELFRONT, GEO_SORAJEWELBACK, GEO_SORAJEWEL, GEO_XWING,
GEO_XWINGFLY, GEO_GLASS, GEO_GLOBE, GEO_PROJECTOR,
GEO_COUNTER, GEO_SOFA, GEO_QUESTLADY, GEO_ENGINEER,
GEO_ENGINEER_LEGLEFT, GEO_ENGINEER_LEGRIGHT, GEO_ENGINEER_ARMLEFT, GEO_ENGINEER_ARMRIGHT,
GEO_ENGINEER_BODY, GEO_COMMANDER, GEO_NORMALDUDE, GEO_KEG,
GEO_BEERFULL, GEO_BEEREMPTY, GEO_MAINICONSJ, GEO_MINIMAPSJ,
GEO_XWINGBODY, GEO_XWING1, GEO_XWING2, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF,
U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT2_POSITION, U_LIGHT2_COLOR,
U_LIGHT2_POWER, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ,
U_LIGHT2_TYPE, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER,
U_LIGHT2_EXPONENT, U_NUMLIGHTS, U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE,
U_TEXT_ENABLED, U_TEXT_COLOR, U_TOTAL
}
enum Interactions {
INTERACT_QUESTLADY, INTERACT_ENGINEER1, INTERACT_ENGINEER2, INTERACT_COMMANDO,
INTERACT_KEG, INTERACT_XWING, INTERACT_BEER
}
Private Member Functions
void renderMesh (Mesh *mesh, bool enableLight)
Renders the GEOMETRY or mesh to the Scene.
void lighting ()
In case of changes to current light, the light will change accordingly.
void lighting2 ()
In case of changes to current light, the light will change accordingly.
void RenderSkybox ()
Renders skybox and is placed separately to prevent confusion.
void RenderText (Mesh *mesh, std::string text, Color color)
Render Text in the world space.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
Renders text to the screen.
void renderminimaptoscreen ()
Renders minimap to the top right of screen.
void MunInit ()
void MunRender ()
void GalaxyInit ()
void GalaxyRender ()
void SoraJewelInit ()
void SoraJewelRender ()
void Renderengineers ()
Renders engineer, this function is placed in the Render()
void Engineeranimation (float dt)
This function is placed in Update(double dt) to run Engineer's animation to walk to ship.
Private Attributes
Light light [2]
bool enableLight = false
float LSPEED = 10.f
int fps = 0
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Camera3 camera
std::stringstream ssDialogue
std::stringstream ssEngiDialogue
std::stringstream ssEngiDialogue2
std::stringstream ssCommandoDialogue
std::string sDialogue
std::string sEngiDialogue
std::string sEngiDialogue2
std::string sCommandoDialogue
std::vector< std::string > Textstuffs
std::vector< std::string > TextEngi
std::vector< std::string > TextEngi2
std::vector< std::string > TextCommando
std::vector< std::string >::iterator position
std::vector< std::string >::iterator Engipos
std::vector< std::string >::iterator Engi2pos
std::vector< std::string >::iterator Commandopos
bool pressE
bool talkwithQL
bool talkwithEngi1
bool talkwithEngi2
bool talkwithCommando
size_t i = 1
size_t j = 1
size_t k = 1
size_t l = 1
float timer = 0.f
bool cutscene
bool timercheck = false
float boxX = 0
float boxZ = 0
int camPosX = 0
int camPosY = 0
int camPosZ = 0
float rotateGlobeY = 0
bool Quest1
bool Quest1Done
bool Quest2
bool Quest2Done
bool QuestsDone
bool TextQ1Activated
bool TextQ2Activated
bool givenBeer
bool EmptyinHand
bool BeerinHand
float Engineerpositionx
float Engineerpositiony
float Engineerpositionz
bool characterismoving = false
bool rotationarmmax = true
bool rotationarmmax2 = true
bool rotationlegmaxleft = true
bool rotationlegmaxright = true
bool engineer1maxy = false
float Engineerrotationarmleft
float Engineerrotationarmright
float Engineerrotationlegleft
float Engineerrotationlegright
float Engineerrotationy
float Engineerpositionx2
float Engineerpositiony2
float Engineerpositionz2
float Engineerrotationy2
int interact = 0
Vector3 tempview
Vector3 viewAtQuestLady
Vector3 viewAtEngineer
Vector3 viewAtCommando
Vector3 viewAtKeg
Vector3 viewAtXwing
Vector3 viewAtBeer
float RadiusFromQuestLady
float RadiusFromEngineer
float RadiusFromCommando
float RadiusFromKeg
float RadiusFromXwing
float RadiusFromBeer
float RotationWings1
float RotationWings2
MS modelStack
MS viewStack
MS projectionStack
Vector3 QuestLady = Vector3(13, -1, -53)
Vector3 Engineer = Vector3(-96, 5, -40)
Vector3 Commando = Vector3(-93, 13, 41)
Vector3 Keg = Vector3(-50, 0, -104)
Vector3 Xwing = Vector3(-85, 19, 65)
Vector3 Beer = Vector3(18, 8, -33)
Detailed Description
Defines the scene Sora Jewel and its methods.
Class SceneSoraJewel:
Definition at line 30 of file SceneSoraJewel.h.
Member Enumeration Documentation
enum SceneSoraJewel::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_QUAD
GEO_LIGHTBALL
GEO_TEXT
GEO_SORAJEWELLEFT
GEO_SORAJEWELRIGHT
GEO_SORAJEWELTOP
GEO_SORAJEWELBOTTOM
GEO_SORAJEWELFRONT
GEO_SORAJEWELBACK
GEO_SORAJEWEL
GEO_XWING
GEO_XWINGFLY
GEO_GLASS
GEO_GLOBE
GEO_PROJECTOR
GEO_COUNTER
GEO_SOFA
GEO_QUESTLADY
GEO_ENGINEER
GEO_ENGINEER_LEGLEFT
GEO_ENGINEER_LEGRIGHT
GEO_ENGINEER_ARMLEFT
GEO_ENGINEER_ARMRIGHT
GEO_ENGINEER_BODY
GEO_COMMANDER
GEO_NORMALDUDE
GEO_KEG
GEO_BEERFULL
GEO_BEEREMPTY
GEO_MAINICONSJ
GEO_MINIMAPSJ
GEO_XWINGBODY
GEO_XWING1
GEO_XWING2
NUM_GEOMETRY
Definition at line 32 of file SceneSoraJewel.h.
enum SceneSoraJewel::Interactions private
Enumerator
INTERACT_QUESTLADY
INTERACT_ENGINEER1
INTERACT_ENGINEER2
INTERACT_COMMANDO
INTERACT_KEG
INTERACT_XWING
INTERACT_BEER
Definition at line 123 of file SceneSoraJewel.h.
enum SceneSoraJewel::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_LIGHT2_POSITION
U_LIGHT2_COLOR
U_LIGHT2_POWER
U_LIGHT2_KC
U_LIGHT2_KL
U_LIGHT2_KQ
U_LIGHT2_TYPE
U_LIGHT2_SPOTDIRECTION
U_LIGHT2_COSCUTOFF
U_LIGHT2_COSINNER
U_LIGHT2_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 72 of file SceneSoraJewel.h.
Constructor & Destructor Documentation
SceneSoraJewel::SceneSoraJewel ()
constructor for the .cpp file
Definition at line 25 of file SceneSoraJewel.cpp.
SceneSoraJewel::~SceneSoraJewel ()
deconstructor for the .cpp file
Definition at line 34 of file SceneSoraJewel.cpp.
Member Function Documentation
void SceneSoraJewel::Engineeranimation (float dt) private
This function is placed in Update(double dt) to run Engineer's animation to walk to ship.
Parameters
double dt
Exceptions
Definition at line 711 of file SceneSoraJewel.cpp.
References characterismoving, engineer1maxy, Engineerpositionx, Engineerpositiony, Engineerpositiony2, Engineerpositionz, Engineerrotationarmleft, Engineerrotationarmright, Engineerrotationlegleft, Engineerrotationlegright, Engineerrotationy, interactions(), QuestsDone, rotationarmmax, rotationarmmax2, rotationlegmaxleft, and rotationlegmaxright.
Referenced by Update().
void SceneSoraJewel::Exit () virtual
Clears whatever is done in init, render and update.
Parameters
Implements Scene.
Definition at line 1557 of file SceneSoraJewel.cpp.
References m_programID, and m_vertexArrayID.
void SceneSoraJewel::GalaxyInit () private
void SceneSoraJewel::GalaxyRender () private
void SceneSoraJewel::Init () virtual
This function initialises everything needed for the scene.
Parameters
Implements Scene.
Definition at line 49 of file SceneSoraJewel.cpp.
References BeerinHand, camera, Light::color, Commandopos, Light::cosCutoff, Light::cosInner, cutscene, Math::DegreeToRadian(), EmptyinHand, Engi2pos, Engineerpositionx, Engineerpositionx2, Engineerpositiony, Engineerpositiony2, Engineerpositionz, Engineerpositionz2, Engineerrotationarmleft, Engineerrotationarmright, Engineerrotationlegleft, Engineerrotationlegright, Engineerrotationy, Engineerrotationy2, Engipos, Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_AXES, GEO_BEEREMPTY, GEO_BEERFULL, GEO_COMMANDER, GEO_COUNTER, GEO_ENGINEER, GEO_ENGINEER_ARMLEFT, GEO_ENGINEER_ARMRIGHT, GEO_ENGINEER_BODY, GEO_ENGINEER_LEGLEFT, GEO_ENGINEER_LEGRIGHT, GEO_GLASS, GEO_GLOBE, GEO_KEG, GEO_LIGHTBALL, GEO_MAINICONSJ, GEO_MINIMAPSJ, GEO_NORMALDUDE, GEO_PROJECTOR, GEO_QUAD, GEO_QUESTLADY, GEO_SOFA, GEO_SORAJEWEL, GEO_SORAJEWELBACK, GEO_SORAJEWELBOTTOM, GEO_SORAJEWELFRONT, GEO_SORAJEWELLEFT, GEO_SORAJEWELRIGHT, GEO_SORAJEWELTOP, GEO_TEXT, GEO_XWING, GEO_XWING1, GEO_XWING2, GEO_XWINGBODY, givenBeer, Camera3::Init(), Material::kAmbient, Light::kC, Material::kDiffuse, Light::kL, Light::kQ, Material::kShininess, Material::kSpecular, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, Mesh::material, meshList, Camera3::minimapsoracoords, Light::position, position, Light::power, pressE, projectionStack, Quest1, Quest1Done, Quest2, Quest2Done, QuestsDone, ReadFromTxt(), RotationWings1, RotationWings2, Camera3::SceneGalaxy, Camera3::SceneMun, Camera3::SceneSoraJewel, sCommandoDialogue, sDialogue, sEngiDialogue, sEngiDialogue2, Component::Set(), Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, ssCommandoDialogue, ssDialogue, ssEngiDialogue, ssEngiDialogue2, talkwithCommando, talkwithEngi1, talkwithEngi2, talkwithQL, TextCommando, TextEngi, TextEngi2, Textstuffs, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHT2_COLOR, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ, U_LIGHT2_POSITION, U_LIGHT2_POWER, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, Vector3::x, and Vector3::y.
void SceneSoraJewel::interactions ()
This function is responsible for using view to do interaction instead of using an area.
Parameters
Definition at line 1574 of file SceneSoraJewel.cpp.
References Beer, BeerinHand, camera, Commando, cutscene, EmptyinHand, Engineer, interact, INTERACT_BEER, INTERACT_COMMANDO, INTERACT_ENGINEER1, INTERACT_ENGINEER2, INTERACT_KEG, INTERACT_QUESTLADY, INTERACT_XWING, Application::IsKeyPressed(), Keg, Camera::position, pressE, Quest1, Quest1Done, Quest2, Quest2Done, QuestLady, QuestsDone, RadiusFromBeer, RadiusFromCommando, RadiusFromEngineer, RadiusFromKeg, RadiusFromQuestLady, RadiusFromXwing, talkwithCommando, talkwithEngi1, talkwithEngi2, talkwithQL, Camera::target, tempview, viewAtBeer, viewAtCommando, viewAtEngineer, viewAtKeg, viewAtQuestLady, viewAtXwing, and Xwing.
Referenced by Engineeranimation().
void SceneSoraJewel::lighting () private
In case of changes to current light, the light will change accordingly.
Parameters
Definition at line 834 of file SceneSoraJewel.cpp.
References light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, m_parameters, Light::position, position, Light::spotDirection, MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, viewStack, Position::x, Vector3::x, Position::y, and Position::z.
Referenced by Render().
void SceneSoraJewel::lighting2 () private
In case of changes to current light, the light will change accordingly.
Parameters
Definition at line 868 of file SceneSoraJewel.cpp.
References light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, m_parameters, Light::position, position, Light::spotDirection, MS::Top(), U_LIGHT1_POSITION, U_LIGHT1_SPOTDIRECTION, viewStack, Position::x, Vector3::x, Position::y, and Position::z.
Referenced by Render().
void SceneSoraJewel::MunInit () private
void SceneSoraJewel::MunRender () private
void SceneSoraJewel::Render () virtual
This function is the main and is responsible for getting the OBJ and or mesh to the sccene.
Parameters
Implements Scene.
Definition at line 1052 of file SceneSoraJewel.cpp.
References camera, camPosX, camPosY, camPosZ, Commando, Engineer, fps, GEO_COMMANDER, GEO_COUNTER, GEO_ENGINEER, GEO_GLASS, GEO_GLOBE, GEO_KEG, GEO_LIGHTBALL, GEO_NORMALDUDE, GEO_PROJECTOR, GEO_QUESTLADY, GEO_SOFA, GEO_SORAJEWEL, GEO_TEXT, GEO_XWING1, GEO_XWING2, GEO_XWINGBODY, Keg, light, lighting(), lighting2(), MS::LoadIdentity(), MS::LookAt(), meshList, modelStack, MS::PopMatrix(), Light::position, Camera::position, position, pressE, MS::PushMatrix(), QuestLady, QuestsDone, Renderengineers(), renderLast(), renderMesh(), renderminimaptoscreen(), RenderSkybox(), renderText(), RenderTextOnScreen(), MS::Rotate(), rotateGlobeY, RotationWings1, RotationWings2, MS::Scale(), Mtx44::SetToIdentity(), Mtx44::SetToPerspective(), Camera::target, MS::Translate(), Camera::up, viewStack, Vector3::x, Xwing, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneSoraJewel::Renderengineers () private
Renders engineer, this function is placed in the Render()
Parameters
Definition at line 1360 of file SceneSoraJewel.cpp.
References Engineerpositionx, Engineerpositionx2, Engineerpositiony, Engineerpositiony2, Engineerpositionz, Engineerpositionz2, Engineerrotationarmleft, Engineerrotationarmright, Engineerrotationlegleft, Engineerrotationlegright, Engineerrotationy, Engineerrotationy2, GEO_ENGINEER_ARMLEFT, GEO_ENGINEER_ARMRIGHT, GEO_ENGINEER_BODY, GEO_ENGINEER_LEGLEFT, GEO_ENGINEER_LEGRIGHT, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneSoraJewel::renderLast ()
This function is placed in the Render() near the end so that we can avoid depth problems.
Parameters
Definition at line 1242 of file SceneSoraJewel.cpp.
References Beer, BeerinHand, EmptyinHand, GEO_BEEREMPTY, GEO_BEERFULL, MS::LoadIdentity(), MS::LoadMatrix(), meshList, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), viewStack, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SceneSoraJewel::renderMesh (Mesh * mesh, bool enableLight) private
Renders the GEOMETRY or mesh to the Scene.
Parameters
Mesh *mesh bool enablelight
Exceptions
Definition at line 903 of file SceneSoraJewel.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), Renderengineers(), renderLast(), renderminimaptoscreen(), RenderSkybox(), and renderText().
void SceneSoraJewel::renderminimaptoscreen () private
Renders minimap to the top right of screen.
Parameters
Definition at line 1447 of file SceneSoraJewel.cpp.
References camera, GEO_MAINICONSJ, GEO_MINIMAPSJ, MS::LoadIdentity(), MS::LoadMatrix(), meshList, Camera3::minimapsoracoords, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), viewStack, Vector3::x, and Vector3::y.
Referenced by Render().
void SceneSoraJewel::renderNPCAnimations ()
void SceneSoraJewel::RenderSkybox () private
Renders skybox and is placed separately to prevent confusion.
Parameters
Definition at line 1496 of file SceneSoraJewel.cpp.
References GEO_SORAJEWELBACK, GEO_SORAJEWELBOTTOM, GEO_SORAJEWELFRONT, GEO_SORAJEWELLEFT, GEO_SORAJEWELRIGHT, GEO_SORAJEWELTOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneSoraJewel::renderText ()
This function renders the textbox and the chat.
Parameters
Definition at line 1311 of file SceneSoraJewel.cpp.
References GEO_QUAD, GEO_TEXT, MS::LoadIdentity(), MS::LoadMatrix(), meshList, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), ssCommandoDialogue, ssDialogue, ssEngiDialogue, ssEngiDialogue2, talkwithCommando, talkwithEngi1, talkwithEngi2, talkwithQL, MS::Translate(), and viewStack.
Referenced by Render().
void SceneSoraJewel::RenderText (Mesh * mesh, std::string text, Color color) private
Render Text in the world space.
Parameters
Mesh* mesh std::string text Color color
Exceptions
Definition at line 956 of file SceneSoraJewel.cpp.
References Mtx44::a, i, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SceneSoraJewel::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Renders text to the screen.
Parameters
Mesh* mesh std::string text Color color float size float x float y
Exceptions
Definition at line 999 of file SceneSoraJewel.cpp.
References Mtx44::a, i, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), and renderText().
void SceneSoraJewel::skybox ()
void SceneSoraJewel::SoraJewelInit () private
void SceneSoraJewel::SoraJewelRender () private
void SceneSoraJewel::Update (double dt) virtual
This function is constantly running to update the scene such as animation and game logics.
Parameters
double dt
Exceptions
Implements Scene.
Definition at line 454 of file SceneSoraJewel.cpp.
References camera, camPosX, camPosY, camPosZ, Commandopos, Gamemode::currentgamestate, cutscene, enableLight, Engi2pos, Engineeranimation(), Engipos, fps, Gamemode::getinstance(), i, Camera3::Init(), interact, INTERACT_XWING, Application::IsKeyPressed(), j, k, l, light, LSPEED, Camera3::minimapsoracoords, Light::position, Camera::position, position, pressE, Quest1Done, Quest2Done, QuestsDone, rotateGlobeY, RotationWings1, RotationWings2, sCommandoDialogue, sDialogue, sEngiDialogue, sEngiDialogue2, Camera3::SJUpdate(), ssCommandoDialogue, ssDialogue, ssEngiDialogue, ssEngiDialogue2, talkwithCommando, talkwithEngi1, talkwithEngi2, talkwithQL, TextCommando, TextEngi, TextEngi2, Textstuffs, timer, Camera::up, Vector3::x, Xwing, Vector3::y, Position::z, and Vector3::z.
Field Documentation
Vector3 SceneSoraJewel::Beer = Vector3(18, 8, -33) private
Definition at line 282 of file SceneSoraJewel.h.
Referenced by interactions(), and renderLast().
bool SceneSoraJewel::BeerinHand private
Definition at line 239 of file SceneSoraJewel.h.
Referenced by Init(), interactions(), and renderLast().
float SceneSoraJewel::boxX = 0 private
Definition at line 207 of file SceneSoraJewel.h.
float SceneSoraJewel::boxZ = 0 private
Definition at line 208 of file SceneSoraJewel.h.
Camera3 SceneSoraJewel::camera private
Definition at line 169 of file SceneSoraJewel.h.
Referenced by Init(), interactions(), Render(), renderminimaptoscreen(), and Update().
int SceneSoraJewel::camPosX = 0 private
Definition at line 209 of file SceneSoraJewel.h.
Referenced by Render(), and Update().
int SceneSoraJewel::camPosY = 0 private
Definition at line 210 of file SceneSoraJewel.h.
Referenced by Render(), and Update().
int SceneSoraJewel::camPosZ = 0 private
Definition at line 211 of file SceneSoraJewel.h.
Referenced by Render(), and Update().
bool SceneSoraJewel::characterismoving = false private
Definition at line 242 of file SceneSoraJewel.h.
Referenced by Engineeranimation().
Vector3 SceneSoraJewel::Commando = Vector3(-93, 13, 41) private
Definition at line 279 of file SceneSoraJewel.h.
Referenced by interactions(), and Render().
std::vector<std::string>::iterator SceneSoraJewel::Commandopos private
Definition at line 189 of file SceneSoraJewel.h.
Referenced by Init(), and Update().
bool SceneSoraJewel::cutscene private
Definition at line 204 of file SceneSoraJewel.h.
Referenced by Init(), interactions(), and Update().
bool SceneSoraJewel::EmptyinHand private
Definition at line 238 of file SceneSoraJewel.h.
Referenced by Init(), interactions(), and renderLast().
bool SceneSoraJewel::enableLight = false private
Definition at line 150 of file SceneSoraJewel.h.
Referenced by Update().
std::vector<std::string>::iterator SceneSoraJewel::Engi2pos private
Definition at line 188 of file SceneSoraJewel.h.
Referenced by Init(), and Update().
Vector3 SceneSoraJewel::Engineer = Vector3(-96, 5, -40) private
Definition at line 278 of file SceneSoraJewel.h.
Referenced by interactions(), and Render().
bool SceneSoraJewel::engineer1maxy = false private
Definition at line 244 of file SceneSoraJewel.h.
Referenced by Engineeranimation().
float SceneSoraJewel::Engineerpositionx private
Definition at line 241 of file SceneSoraJewel.h.
Referenced by Engineeranimation(), Init(), and Renderengineers().
float SceneSoraJewel::Engineerpositionx2 private
Definition at line 246 of file SceneSoraJewel.h.
Referenced by Init(), and Renderengineers().
float SceneSoraJewel::Engineerpositiony private
Definition at line 241 of file SceneSoraJewel.h.
Referenced by Engineeranimation(), Init(), and Renderengineers().
float SceneSoraJewel::Engineerpositiony2 private
Definition at line 246 of file SceneSoraJewel.h.
Referenced by Engineeranimation(), Init(), and Renderengineers().
float SceneSoraJewel::Engineerpositionz private
Definition at line 241 of file SceneSoraJewel.h.
Referenced by Engineeranimation(), Init(), and Renderengineers().
float SceneSoraJewel::Engineerpositionz2 private
Definition at line 246 of file SceneSoraJewel.h.
Referenced by Init(), and Renderengineers().
float SceneSoraJewel::Engineerrotationarmleft private
Definition at line 245 of file SceneSoraJewel.h.
Referenced by Engineeranimation(), Init(), and Renderengineers().
float SceneSoraJewel::Engineerrotationarmright private
Definition at line 245 of file SceneSoraJewel.h.
Referenced by Engineeranimation(), Init(), and Renderengineers().
float SceneSoraJewel::Engineerrotationlegleft private
Definition at line 245 of file SceneSoraJewel.h.
Referenced by Engineeranimation(), Init(), and Renderengineers().
float SceneSoraJewel::Engineerrotationlegright private
Definition at line 245 of file SceneSoraJewel.h.
Referenced by Engineeranimation(), Init(), and Renderengineers().
float SceneSoraJewel::Engineerrotationy private
Definition at line 245 of file SceneSoraJewel.h.
Referenced by Engineeranimation(), Init(), and Renderengineers().
float SceneSoraJewel::Engineerrotationy2 private
Definition at line 246 of file SceneSoraJewel.h.
Referenced by Init(), and Renderengineers().
std::vector<std::string>::iterator SceneSoraJewel::Engipos private
Definition at line 187 of file SceneSoraJewel.h.
Referenced by Init(), and Update().
int SceneSoraJewel::fps = 0 private
Definition at line 152 of file SceneSoraJewel.h.
Referenced by Render(), and Update().
bool SceneSoraJewel::givenBeer private
Definition at line 237 of file SceneSoraJewel.h.
Referenced by Init().
size_t SceneSoraJewel::i = 1 private
Definition at line 198 of file SceneSoraJewel.h.
Referenced by RenderText(), RenderTextOnScreen(), and Update().
int SceneSoraJewel::interact = 0 private
Definition at line 248 of file SceneSoraJewel.h.
Referenced by interactions(), and Update().
size_t SceneSoraJewel::j = 1 private
Definition at line 199 of file SceneSoraJewel.h.
Referenced by Update().
size_t SceneSoraJewel::k = 1 private
Definition at line 200 of file SceneSoraJewel.h.
Referenced by Update().
Vector3 SceneSoraJewel::Keg = Vector3(-50, 0, -104) private
Definition at line 280 of file SceneSoraJewel.h.
Referenced by interactions(), and Render().
size_t SceneSoraJewel::l = 1 private
Definition at line 201 of file SceneSoraJewel.h.
Referenced by Update().
Light SceneSoraJewel::light[2] private
Definition at line 149 of file SceneSoraJewel.h.
Referenced by Init(), lighting(), lighting2(), Render(), and Update().
float SceneSoraJewel::LSPEED = 10.f private
Definition at line 151 of file SceneSoraJewel.h.
Referenced by Update().
unsigned SceneSoraJewel::m_parameters[U_TOTAL] private
Definition at line 167 of file SceneSoraJewel.h.
Referenced by Init(), lighting(), lighting2(), renderMesh(), RenderText(), and RenderTextOnScreen().
unsigned SceneSoraJewel::m_programID private
Definition at line 166 of file SceneSoraJewel.h.
Referenced by Exit(), and Init().
unsigned SceneSoraJewel::m_vertexArrayID private
Definition at line 163 of file SceneSoraJewel.h.
Referenced by Exit(), and Init().
Mesh* SceneSoraJewel::meshList[NUM_GEOMETRY] private
Definition at line 164 of file SceneSoraJewel.h.
Referenced by Init(), Render(), Renderengineers(), renderLast(), renderminimaptoscreen(), RenderSkybox(), and renderText().
MS SceneSoraJewel::modelStack private
Definition at line 275 of file SceneSoraJewel.h.
Referenced by Render(), Renderengineers(), renderLast(), renderMesh(), renderminimaptoscreen(), RenderSkybox(), renderText(), RenderText(), and RenderTextOnScreen().
std::vector<std::string>::iterator SceneSoraJewel::position private
Definition at line 186 of file SceneSoraJewel.h.
Referenced by Init(), lighting(), lighting2(), Render(), and Update().
bool SceneSoraJewel::pressE private
Definition at line 191 of file SceneSoraJewel.h.
Referenced by Init(), interactions(), Render(), and Update().
MS SceneSoraJewel::projectionStack private
Definition at line 275 of file SceneSoraJewel.h.
Referenced by Init(), renderLast(), renderMesh(), renderminimaptoscreen(), renderText(), RenderText(), and RenderTextOnScreen().
bool SceneSoraJewel::Quest1 private
Definition at line 228 of file SceneSoraJewel.h.
Referenced by Init(), and interactions().
bool SceneSoraJewel::Quest1Done private
Definition at line 229 of file SceneSoraJewel.h.
Referenced by Init(), interactions(), and Update().
bool SceneSoraJewel::Quest2 private
Definition at line 230 of file SceneSoraJewel.h.
Referenced by Init(), and interactions().
bool SceneSoraJewel::Quest2Done private
Definition at line 231 of file SceneSoraJewel.h.
Referenced by Init(), interactions(), and Update().
Vector3 SceneSoraJewel::QuestLady = Vector3(13, -1, -53) private
Definition at line 277 of file SceneSoraJewel.h.
Referenced by interactions(), and Render().
bool SceneSoraJewel::QuestsDone private
Definition at line 232 of file SceneSoraJewel.h.
Referenced by Engineeranimation(), Init(), interactions(), Render(), and Update().
float SceneSoraJewel::RadiusFromBeer private
Definition at line 263 of file SceneSoraJewel.h.
Referenced by interactions().
float SceneSoraJewel::RadiusFromCommando private
Definition at line 260 of file SceneSoraJewel.h.
Referenced by interactions().
float SceneSoraJewel::RadiusFromEngineer private
Definition at line 259 of file SceneSoraJewel.h.
Referenced by interactions().
float SceneSoraJewel::RadiusFromKeg private
Definition at line 261 of file SceneSoraJewel.h.
Referenced by interactions().
float SceneSoraJewel::RadiusFromQuestLady private
Definition at line 258 of file SceneSoraJewel.h.
Referenced by interactions().
float SceneSoraJewel::RadiusFromXwing private
Definition at line 262 of file SceneSoraJewel.h.
Referenced by interactions().
float SceneSoraJewel::rotateGlobeY = 0 private
Definition at line 213 of file SceneSoraJewel.h.
Referenced by Render(), and Update().
bool SceneSoraJewel::rotationarmmax = true private
Definition at line 242 of file SceneSoraJewel.h.
Referenced by Engineeranimation().
bool SceneSoraJewel::rotationarmmax2 = true private
Definition at line 243 of file SceneSoraJewel.h.
Referenced by Engineeranimation().
bool SceneSoraJewel::rotationlegmaxleft = true private
Definition at line 243 of file SceneSoraJewel.h.
Referenced by Engineeranimation().
bool SceneSoraJewel::rotationlegmaxright = true private
Definition at line 243 of file SceneSoraJewel.h.
Referenced by Engineeranimation().
float SceneSoraJewel::RotationWings1 private
Definition at line 265 of file SceneSoraJewel.h.
Referenced by Init(), Render(), and Update().
float SceneSoraJewel::RotationWings2 private
Definition at line 266 of file SceneSoraJewel.h.
Referenced by Init(), Render(), and Update().
std::string SceneSoraJewel::sCommandoDialogue private
Definition at line 179 of file SceneSoraJewel.h.
Referenced by Init(), and Update().
std::string SceneSoraJewel::sDialogue private
Definition at line 176 of file SceneSoraJewel.h.
Referenced by Init(), and Update().
std::string SceneSoraJewel::sEngiDialogue private
Definition at line 177 of file SceneSoraJewel.h.
Referenced by Init(), and Update().
std::string SceneSoraJewel::sEngiDialogue2 private
Definition at line 178 of file SceneSoraJewel.h.
Referenced by Init(), and Update().
std::stringstream SceneSoraJewel::ssCommandoDialogue private
Definition at line 174 of file SceneSoraJewel.h.
Referenced by Init(), renderText(), and Update().
std::stringstream SceneSoraJewel::ssDialogue private
Definition at line 171 of file SceneSoraJewel.h.
Referenced by Init(), renderText(), and Update().
std::stringstream SceneSoraJewel::ssEngiDialogue private
Definition at line 172 of file SceneSoraJewel.h.
Referenced by Init(), renderText(), and Update().
std::stringstream SceneSoraJewel::ssEngiDialogue2 private
Definition at line 173 of file SceneSoraJewel.h.
Referenced by Init(), renderText(), and Update().
bool SceneSoraJewel::talkwithCommando private
Definition at line 196 of file SceneSoraJewel.h.
Referenced by Init(), interactions(), renderText(), and Update().
bool SceneSoraJewel::talkwithEngi1 private
Definition at line 194 of file SceneSoraJewel.h.
Referenced by Init(), interactions(), renderText(), and Update().
bool SceneSoraJewel::talkwithEngi2 private
Definition at line 195 of file SceneSoraJewel.h.
Referenced by Init(), interactions(), renderText(), and Update().
bool SceneSoraJewel::talkwithQL private
Definition at line 193 of file SceneSoraJewel.h.
Referenced by Init(), interactions(), renderText(), and Update().
Vector3 SceneSoraJewel::tempview private
Definition at line 250 of file SceneSoraJewel.h.
Referenced by interactions().
std::vector<std::string> SceneSoraJewel::TextCommando private
Definition at line 184 of file SceneSoraJewel.h.
Referenced by Init(), and Update().
std::vector<std::string> SceneSoraJewel::TextEngi private
Definition at line 182 of file SceneSoraJewel.h.
Referenced by Init(), and Update().
std::vector<std::string> SceneSoraJewel::TextEngi2 private
Definition at line 183 of file SceneSoraJewel.h.
Referenced by Init(), and Update().
bool SceneSoraJewel::TextQ1Activated private
Definition at line 234 of file SceneSoraJewel.h.
bool SceneSoraJewel::TextQ2Activated private
Definition at line 235 of file SceneSoraJewel.h.
std::vector<std::string> SceneSoraJewel::Textstuffs private
Definition at line 181 of file SceneSoraJewel.h.
Referenced by Init(), and Update().
float SceneSoraJewel::timer = 0.f private
Definition at line 203 of file SceneSoraJewel.h.
Referenced by Update().
bool SceneSoraJewel::timercheck = false private
Definition at line 205 of file SceneSoraJewel.h.
Vector3 SceneSoraJewel::viewAtBeer private
Definition at line 256 of file SceneSoraJewel.h.
Referenced by interactions().
Vector3 SceneSoraJewel::viewAtCommando private
Definition at line 253 of file SceneSoraJewel.h.
Referenced by interactions().
Vector3 SceneSoraJewel::viewAtEngineer private
Definition at line 252 of file SceneSoraJewel.h.
Referenced by interactions().
Vector3 SceneSoraJewel::viewAtKeg private
Definition at line 254 of file SceneSoraJewel.h.
Referenced by interactions().
Vector3 SceneSoraJewel::viewAtQuestLady private
Definition at line 251 of file SceneSoraJewel.h.
Referenced by interactions().
Vector3 SceneSoraJewel::viewAtXwing private
Definition at line 255 of file SceneSoraJewel.h.
Referenced by interactions().
MS SceneSoraJewel::viewStack private
Definition at line 275 of file SceneSoraJewel.h.
Referenced by lighting(), lighting2(), Render(), renderLast(), renderMesh(), renderminimaptoscreen(), renderText(), RenderText(), and RenderTextOnScreen().
Vector3 SceneSoraJewel::Xwing = Vector3(-85, 19, 65) private
Definition at line 281 of file SceneSoraJewel.h.
Referenced by interactions(), Render(), and Update().
The documentation for this class was generated from the following files:
LiZhaoyuan1/Source/SceneSoraJewel.h
LiZhaoyuan1/Source/SceneSoraJewel.cpp