My Application: Gamemode Class Reference
Gamemode Class Reference
Defines the Gamemode and its methods.
#include <CurrentGameState.h>
Static Public Member Functions
static Gamemode * getinstance ()
Data Fields
int currentgamestate = 0
Private Member Functions
Gamemode ()
Detailed Description
Defines the Gamemode and its methods.
Class Gamemode:
Definition at line 19 of file CurrentGameState.h.
Constructor & Destructor Documentation
Gamemode::Gamemode () inline private
Definition at line 29 of file CurrentGameState.h.
Member Function Documentation
static Gamemode* Gamemode::getinstance () inline static
Definition at line 22 of file CurrentGameState.h.
Referenced by SceneGalaxy::CutScene(), Application::Run(), SP2::Update(), LoadingScreen::Update(), SceneMun::Update(), and SceneSoraJewel::Update().
Field Documentation
int Gamemode::currentgamestate = 0
Definition at line 27 of file CurrentGameState.h.
Referenced by SceneGalaxy::CutScene(), SP2::Update(), LoadingScreen::Update(), SceneMun::Update(), and SceneSoraJewel::Update().
The documentation for this class was generated from the following file:
LiZhaoyuan1/Source/CurrentGameState.h