My Application: Application Class Reference
Application Class Reference
#include <Application.h>
Public Member Functions
Application ()
~Application ()
void Init ()
void Run ()
void Exit ()
void changescenes ()
Static Public Member Functions
static bool IsKeyPressed (unsigned short key)
Data Fields
bool sceneischanged = false
Private Attributes
StopWatch m_timer
music playmusic
Detailed Description
Definition at line 7 of file Application.h.
Constructor & Destructor Documentation
Application::Application ()
Definition at line 45 of file Application.cpp.
Application::~Application ()
Definition at line 49 of file Application.cpp.
Member Function Documentation
void Application::changescenes ()
void Application::Exit ()
Definition at line 239 of file Application.cpp.
References m_window.
Referenced by main(), and SP2::Update().
void Application::Init ()
Definition at line 58 of file Application.cpp.
References error_callback(), m_window, primary, and resize_callback().
Referenced by main().
bool Application::IsKeyPressed (unsigned short key) static
Definition at line 40 of file Application.cpp.
Referenced by SceneSoraJewel::interactions(), SceneMun::interactions(), SceneGalaxy::QuestDetail(), SceneMun::RenderPickaxeOnScreen(), Run(), Camera3::SJUpdate(), Camera::Update(), Camera3::Update(), SP2::Update(), SceneGalaxy::Update(), SceneMun::Update(), SceneSoraJewel::Update(), Camera3::UpdateCollision(), and Camera3::XWingCamera().
void Application::Run ()
Definition at line 112 of file Application.cpp.
References Scene::Exit(), frameTime, StopWatch::getElapsedTime(), Gamemode::getinstance(), Scene::Init(), IsKeyPressed(), m_timer, m_window, music::musicGalaxy(), music::musicMainMenu(), music::musicMun(), music::musicSoraJewel(), playmusic, Scene::Render(), sceneischanged, StopWatch::startTimer(), Scene::Update(), and StopWatch::waitUntil().
Referenced by main().
Field Documentation
StopWatch Application::m_timer private
Definition at line 20 of file Application.h.
Referenced by Run().
music Application::playmusic private
Definition at line 21 of file Application.h.
Referenced by Run().
bool Application::sceneischanged = false
Definition at line 17 of file Application.h.
Referenced by Run().
The documentation for this class was generated from the following files:
LiZhaoyuan1/Source/Application.h
LiZhaoyuan1/Source/Application.cpp