My Application: music Class Reference
music Class Reference
Defines the music playing and its methods.
#include <Music.h>
Public Member Functions
music ()
music constructor
~music ()
music destructor
void musicInit ()
void musicSoraJewel ()
music function to play music for Sora Jewel scene
void musicGalaxy ()
music function to play music for Galaxy scene
void musicMun ()
music function to play music for Mun scene
void musicMainMenu ()
music function to play music for main menu
Data Fields
ISoundEngine * se
ISoundSource * MusicSoraJewel
ISoundSource * MusicGalaxy
ISoundSource * MusicMun
Detailed Description
Defines the music playing and its methods.
Class music:
Definition at line 28 of file Music.h.
Constructor & Destructor Documentation
music::music ()
music constructor
Definition at line 16 of file Music.cpp.
References irrklang::createIrrKlangDevice(), and se.
music::~music ()
music destructor
Definition at line 25 of file Music.cpp.
References irrklang::IRefCounted::drop(), and se.
Member Function Documentation
void music::musicGalaxy ()
music function to play music for Galaxy scene
Definition at line 45 of file Music.cpp.
References irrklang::ISoundEngine::addSoundSourceFromFile(), MusicGalaxy, irrklang::ISoundEngine::play2D(), se, and irrklang::ISoundEngine::stopAllSounds().
Referenced by Application::Run().
void music::musicInit ()
void music::musicMainMenu ()
music function to play music for main menu
Definition at line 67 of file Music.cpp.
References se, and irrklang::ISoundEngine::stopAllSounds().
Referenced by Application::Run().
void music::musicMun ()
music function to play music for Mun scene
Definition at line 56 of file Music.cpp.
References irrklang::ISoundEngine::addSoundSourceFromFile(), MusicMun, irrklang::ISoundEngine::play2D(), se, and irrklang::ISoundEngine::stopAllSounds().
Referenced by Application::Run().
void music::musicSoraJewel ()
music function to play music for Sora Jewel scene
Definition at line 34 of file Music.cpp.
References irrklang::ISoundEngine::addSoundSourceFromFile(), MusicSoraJewel, irrklang::ISoundEngine::play2D(), se, and irrklang::ISoundEngine::stopAllSounds().
Referenced by Application::Run().
Field Documentation
ISoundSource* music::MusicGalaxy
Definition at line 42 of file Music.h.
Referenced by musicGalaxy().
ISoundSource* music::MusicMun
Definition at line 43 of file Music.h.
Referenced by musicMun().
ISoundSource* music::MusicSoraJewel
Definition at line 41 of file Music.h.
Referenced by musicSoraJewel().
ISoundEngine* music::se
Definition at line 40 of file Music.h.
Referenced by music(), musicGalaxy(), musicMainMenu(), musicMun(), musicSoraJewel(), and ~music().
The documentation for this class was generated from the following files:
LiZhaoyuan1/Source/Music.h
LiZhaoyuan1/Source/Music.cpp