My Application: Camera3 Class Reference
Camera3 Class Reference
Defines the camera and its methods.
#include <Camera3.h>
Public Member Functions
Camera3 ()
Camera3 constructor.
~Camera3 ()
Camera3 destructor.
virtual void Init (const Vector3 &pos, const Vector3 &target, const Vector3 &up)
Camera3 initializer.
virtual void Update (double dt, float bounds)
Camera3 Update function.
virtual void SJUpdate (double dt, float minboundsx, float maxboundsx, float minboundsz, float maxboundsz)
Camera3 SJUpdate funcion.
virtual void Reset ()
Camera3 Reset function.
void XWingCamera (double dt, float bounds)
Camera3 XWingCamera function.
void UpdateCollision (float bounds, double dt)
Camera3 UpdateCollision function.
bool boundaryCheckerX (float smallx, float largex, float smallz, float largez, Vector3 value)
Camera3 boundaryCheckerX function.
bool boundaryCheckerZ (float smallx, float largex, float smallz, float largez, Vector3 value)
Camera3 boundaryCheckerZ function.
bool OBJboundaryX (Vector3 Testvalue)
Camera3 OBJboundaryX function.
bool OBJboundaryZ (Vector3 Testvalue)
Camera3 OBJboundaryZ function.
bool OBJboundaryY (Vector3 Testvalue, int XZ)
Camera3 OBJboundaryY function.
bool AllMunBoundaryX (Vector3 Testvalue)
Camera3 AllMunBoundaryX function.
bool AllMunBoundaryZ (Vector3 Testvalue)
Camera3 AllMunBoundaryZ function.
bool AllSoraJewelBoundaryX (Vector3 Testvalue)
Camera3 AllSoraJewelBoundaryX function.
bool AllSoraJewelBoundaryZ (Vector3 Testvalue)
Camera3 AllSoraJewelBoundaryZ function.
bool OnGround ()
Camera3 OnGround function.
Public Member Functions inherited from Camera
Camera ()
~Camera ()
virtual void Update (double dt)
Data Fields
Vector3 defaultPosition
Vector3 defaultTarget
Vector3 defaultUp
Vector3 currentV = (0.f, 0.f, 0.f)
Vector3 displacement = (0.f, 0.f, 0.f)
Vector3 minimapcoords
Vector3 minimapsoracoords = (78.f, 55.f, -1.f)
bool SceneSoraJewel = false
bool SceneMun = false
bool SceneGalaxy = false
bool jump = false
bool wherecube = true
float rotateChar
float translateChar
float Force
float mass
float gravity
float acceleration
float speed
Data Fields inherited from Camera
Vector3 position
Vector3 target
Vector3 up
Vector3 view
Detailed Description
Defines the camera and its methods.
Class Camera3:
Definition at line 21 of file Camera3.h.
Constructor & Destructor Documentation
Camera3::Camera3 ()
Camera3 constructor.
Definition at line 19 of file Camera3.cpp.
Camera3::~Camera3 ()
Camera3 destructor.
Definition at line 28 of file Camera3.cpp.
Member Function Documentation
bool Camera3::AllMunBoundaryX (Vector3 Testvalue)
Camera3 AllMunBoundaryX function.
Parameters
Testvalue (value of current camera.position)
Returns
true/false
Definition at line 675 of file Camera3.cpp.
References boundaryCheckerX().
Referenced by OBJboundaryX(), and OBJboundaryY().
bool Camera3::AllMunBoundaryZ (Vector3 Testvalue)
Camera3 AllMunBoundaryZ function.
Parameters
Testvalue (value of current camera.position)
Returns
true/false
Definition at line 707 of file Camera3.cpp.
References boundaryCheckerZ().
Referenced by OBJboundaryY(), and OBJboundaryZ().
bool Camera3::AllSoraJewelBoundaryX (Vector3 Testvalue)
Camera3 AllSoraJewelBoundaryX function.
Parameters
Testvalue (value of current camera.position)
Returns
true/false
Definition at line 739 of file Camera3.cpp.
References boundaryCheckerX().
Referenced by OBJboundaryX(), and OBJboundaryY().
bool Camera3::AllSoraJewelBoundaryZ (Vector3 Testvalue)
Camera3 AllSoraJewelBoundaryZ function.
Parameters
Testvalue (value of current camera.position)
Returns
true/false
Definition at line 759 of file Camera3.cpp.
References boundaryCheckerZ().
Referenced by OBJboundaryY(), and OBJboundaryZ().
bool Camera3::boundaryCheckerX (float smallx, float largex, float smallz, float largez, Vector3 value)
Camera3 boundaryCheckerX function.
Parameters
minimum x, maximum x, minimum z, maximum z, vector3 value
Returns
true/false
Definition at line 527 of file Camera3.cpp.
References Vector3::x, and Vector3::z.
Referenced by AllMunBoundaryX(), AllSoraJewelBoundaryX(), and OBJboundaryY().
bool Camera3::boundaryCheckerZ (float smallx, float largex, float smallz, float largez, Vector3 value)
Camera3 boundaryCheckerZ function.
Parameters
minimum x, maximum x, minimum z, maximum z, vector3 value
Returns
true/false
Definition at line 543 of file Camera3.cpp.
References Vector3::x, and Vector3::z.
Referenced by AllMunBoundaryZ(), AllSoraJewelBoundaryZ(), and OBJboundaryY().
void Camera3::Init (const Vector3 & pos, const Vector3 & target, const Vector3 & up) virtual
Camera3 initializer.
Reimplemented from Camera.
Definition at line 37 of file Camera3.cpp.
References Vector3::Cross(), defaultPosition, defaultTarget, defaultUp, Force, gravity, mass, minimapsoracoords, Vector3::Normalize(), Vector3::Normalized(), Camera::position, rotateChar, speed, Camera::target, translateChar, Camera::view, and Vector3::y.
Referenced by SceneGalaxy::CutScene(), SP2::Init(), LoadingScreen::Init(), SceneGalaxy::Init(), SceneMun::Init(), SceneSoraJewel::Init(), SceneMun::Update(), and SceneSoraJewel::Update().
bool Camera3::OBJboundaryX (Vector3 Testvalue)
Camera3 OBJboundaryX function.
Parameters
Testvalue (value of current camera.position)
Returns
true/false
Definition at line 559 of file Camera3.cpp.
References AllMunBoundaryX(), and AllSoraJewelBoundaryX().
Referenced by SJUpdate(), and Update().
bool Camera3::OBJboundaryY (Vector3 Testvalue, int XZ)
Camera3 OBJboundaryY function.
Parameters
Testvalue (value of current camera.position) and int XZ
Returns
true/false
Definition at line 603 of file Camera3.cpp.
References AllMunBoundaryX(), AllMunBoundaryZ(), AllSoraJewelBoundaryX(), AllSoraJewelBoundaryZ(), boundaryCheckerX(), boundaryCheckerZ(), and Vector3::y.
Referenced by SJUpdate(), and Update().
bool Camera3::OBJboundaryZ (Vector3 Testvalue)
Camera3 OBJboundaryZ function.
Parameters
Testvalue (value of current camera.position)
Returns
true/false
Definition at line 581 of file Camera3.cpp.
References AllMunBoundaryZ(), and AllSoraJewelBoundaryZ().
Referenced by SJUpdate(), and Update().
bool Camera3::OnGround ()
Camera3 OnGround function.
Returns
true/false
Definition at line 1089 of file Camera3.cpp.
References Camera::position, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SJUpdate().
void Camera3::Reset () virtual
Camera3 Reset function.
Reimplemented from Camera.
Definition at line 330 of file Camera3.cpp.
References defaultPosition, defaultTarget, defaultUp, Camera::position, Camera::target, Camera::up, and Camera::view.
Referenced by SJUpdate(), Update(), and XWingCamera().
void Camera3::SJUpdate (double dt, float maxboundsx, float minboundsx, float minboundsz, float maxboundsz) virtual
Camera3 SJUpdate funcion.
Parameters
delta time, maxboundsx, minboundsx, minboundsz, maxboundsz
Definition at line 777 of file Camera3.cpp.
References Vector3::Cross(), gravity, Application::IsKeyPressed(), minimapcoords, minimapsoracoords, Vector3::Normalize(), Vector3::Normalized(), OBJboundaryX(), OBJboundaryY(), OBJboundaryZ(), OnGround(), Camera::position, Reset(), rotateChar, Mtx44::SetToRotation(), speed, Camera::target, Camera::up, Camera::view, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SceneSoraJewel::Update().
void Camera3::Update (double dt, float bounds) virtual
Camera3 Update function.
Definition at line 62 of file Camera3.cpp.
References Vector3::Cross(), Application::IsKeyPressed(), minimapcoords, minimapsoracoords, Vector3::Normalize(), Vector3::Normalized(), OBJboundaryX(), OBJboundaryY(), OBJboundaryZ(), Camera::position, Reset(), rotateChar, Mtx44::SetToRotation(), speed, Camera::target, Camera::up, Camera::view, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SceneMun::Update().
void Camera3::UpdateCollision (float bounds, double dt)
Camera3 UpdateCollision function.
Parameters
boundary,double dt
Definition at line 345 of file Camera3.cpp.
References Vector3::Cross(), Application::IsKeyPressed(), minimapcoords, Vector3::Normalize(), Vector3::Normalized(), Camera::position, Camera::target, Camera::up, Camera::view, Vector3::x, Vector3::y, and Vector3::z.
void Camera3::XWingCamera (double dt, float bounds)
Camera3 XWingCamera function.
Parameters
double dt, boundary
Definition at line 439 of file Camera3.cpp.
References Vector3::Cross(), Application::IsKeyPressed(), Vector3::Normalize(), Vector3::Normalized(), Camera::position, Reset(), rotateChar, Mtx44::SetToRotation(), Camera::target, Camera::up, Camera::view, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SceneGalaxy::Update().
Field Documentation
float Camera3::acceleration
Definition at line 74 of file Camera3.h.
Vector3 Camera3::currentV = (0.f, 0.f, 0.f)
Definition at line 32 of file Camera3.h.
Vector3 Camera3::defaultPosition
Definition at line 28 of file Camera3.h.
Referenced by Init(), and Reset().
Vector3 Camera3::defaultTarget
Definition at line 29 of file Camera3.h.
Referenced by Init(), and Reset().
Vector3 Camera3::defaultUp
Definition at line 30 of file Camera3.h.
Referenced by Init(), and Reset().
Vector3 Camera3::displacement = (0.f, 0.f, 0.f)
Definition at line 33 of file Camera3.h.
float Camera3::Force
Definition at line 71 of file Camera3.h.
Referenced by Init().
float Camera3::gravity
Definition at line 73 of file Camera3.h.
Referenced by Init(), and SJUpdate().
bool Camera3::jump = false
Definition at line 65 of file Camera3.h.
float Camera3::mass
Definition at line 72 of file Camera3.h.
Referenced by Init().
Vector3 Camera3::minimapcoords
Definition at line 35 of file Camera3.h.
Referenced by SceneMun::Init(), SceneMun::Renderpicturetoscreen(), SJUpdate(), Update(), and UpdateCollision().
Vector3 Camera3::minimapsoracoords = (78.f, 55.f, -1.f)
Definition at line 36 of file Camera3.h.
Referenced by Init(), SceneSoraJewel::Init(), SceneSoraJewel::renderminimaptoscreen(), SJUpdate(), Update(), and SceneSoraJewel::Update().
float Camera3::rotateChar
Definition at line 68 of file Camera3.h.
Referenced by Init(), SceneGalaxy::RenderMissile(), SceneGalaxy::RenderXwing(), SJUpdate(), Update(), and XWingCamera().
bool Camera3::SceneGalaxy = false
Definition at line 53 of file Camera3.h.
Referenced by SceneGalaxy::Init(), SceneMun::Init(), and SceneSoraJewel::Init().
bool Camera3::SceneMun = false
Definition at line 52 of file Camera3.h.
Referenced by SceneGalaxy::Init(), SceneMun::Init(), and SceneSoraJewel::Init().
bool Camera3::SceneSoraJewel = false
Definition at line 51 of file Camera3.h.
Referenced by SceneGalaxy::Init(), SceneMun::Init(), and SceneSoraJewel::Init().
float Camera3::speed
Definition at line 75 of file Camera3.h.
Referenced by Init(), SJUpdate(), and Update().
float Camera3::translateChar
Definition at line 69 of file Camera3.h.
Referenced by Init().
bool Camera3::wherecube = true
Definition at line 66 of file Camera3.h.
The documentation for this class was generated from the following files:
LiZhaoyuan1/Source/Camera3.h
LiZhaoyuan1/Source/Camera3.cpp