My Application: MeshBuilder Class Reference
MeshBuilder Class Reference
Provides methods to generate mesh of different shapes.
#include <MeshBuilder.h>
Static Public Member Functions
static Mesh * GenerateAxes (const std::string &meshName, float lengthX, float lengthY, float lengthZ)
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateQuad (const std::string &meshName, Color color)
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCube (const std::string &meshName, Color color)
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCircle (const std::string &meshName, Color color, unsigned numSlices=36)
static Mesh * GenerateRing (const std::string &meshName, Color color, float innerRadius, unsigned numSlices=36)
static Mesh * GenerateSphere (const std::string &meshName, Color color, unsigned numStacks=18, unsigned numSlices=36)
static Mesh * GenerateCylinder (const std::string &meshName, Color color, unsigned numSlices=36)
static Mesh * GenerateCone (const std::string &meshName, Color color, unsigned numSlices=36)
static Mesh * GenerateOBJ (const std::string &meshName, const std::string &file_path)
static Mesh * GenerateText (const std::string &meshName, unsigned numRow, unsigned numCol)
static Mesh * GenerateHemiSphere (const std::string &meshName, Color color, unsigned numStacks=18, unsigned numSlices=36)
Detailed Description
Provides methods to generate mesh of different shapes.
Class MeshBuilder:
Definition at line 13 of file MeshBuilder.h.
Member Function Documentation
Mesh * MeshBuilder::GenerateAxes (const std::string & meshName, float lengthX, float lengthY, float lengthZ) static
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - x-axis should start at -lengthX / 2 and end at lengthX / 2
lengthY - y-axis should start at -lengthY / 2 and end at lengthY / 2
lengthZ - z-axis should start at -lengthZ / 2 and end at lengthZ / 2
Returns
Pointer to mesh storing VBO/IBO of reference axes
Definition at line 21 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), Color::Set(), and Mesh::vertexBuffer.
Referenced by SP2::Init(), LoadingScreen::Init(), SceneGalaxy::Init(), SceneMun::Init(), and SceneSoraJewel::Init().
Mesh * MeshBuilder::GenerateCircle (const std::string & meshName, Color color, unsigned numSlices = 36) static
Definition at line 239 of file MeshBuilder.cpp.
References circleX(), circleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCone (const std::string & meshName, Color color, unsigned numSlices = 36) static
Definition at line 481 of file MeshBuilder.cpp.
References circleX(), circleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vector3::Normalized(), Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCube (const std::string & meshName, Color color) static
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of cube
lengthY - height of cube
lengthZ - depth of cube
Returns
Pointer to mesh storing VBO/IBO of cube
Definition at line 163 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by SP2::Init(), LoadingScreen::Init(), SceneGalaxy::Init(), and SceneMun::Init().
Mesh * MeshBuilder::GenerateCylinder (const std::string & meshName, Color color, unsigned numSlices = 36) static
Definition at line 415 of file MeshBuilder.cpp.
References Vertex::color, cylinderX(), cylinderZ(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateHemiSphere (const std::string & meshName, Color color, unsigned numStacks = 18, unsigned numSlices = 36) static
Definition at line 536 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vector3::Normalize(), Vertex::pos, Position::Set(), Vector3::Set(), sphereX(), sphereY(), sphereZ(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateOBJ (const std::string & meshName, const std::string & file_path) static
Definition at line 384 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, IndexVBO(), LoadOBJ(), Mesh::mode, and Mesh::vertexBuffer.
Referenced by LoadingScreen::Init(), SceneGalaxy::Init(), SceneMun::Init(), and SceneSoraJewel::Init().
Mesh * MeshBuilder::GenerateQuad (const std::string & meshName, Color color) static
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of quad
lengthY - height of quad
Returns
Pointer to mesh storing VBO/IBO of quad
Definition at line 67 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by SP2::Init(), LoadingScreen::Init(), SceneGalaxy::Init(), SceneMun::Init(), and SceneSoraJewel::Init().
Mesh * MeshBuilder::GenerateRing (const std::string & meshName, Color color, float innerRadius, unsigned numSlices = 36) static
Definition at line 278 of file MeshBuilder.cpp.
References circleX(), circleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateSphere (const std::string & meshName, Color color, unsigned numStacks = 18, unsigned numSlices = 36) static
Definition at line 333 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vector3::Normalize(), Vertex::pos, Position::Set(), Vector3::Set(), sphereX(), sphereY(), sphereZ(), and Mesh::vertexBuffer.
Referenced by SceneGalaxy::Init(), SceneMun::Init(), and SceneSoraJewel::Init().
Mesh * MeshBuilder::GenerateText (const std::string & meshName, unsigned numRow, unsigned numCol) static
Definition at line 99 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by SP2::Init(), LoadingScreen::Init(), SceneGalaxy::Init(), SceneMun::Init(), and SceneSoraJewel::Init().
The documentation for this class was generated from the following files:
LiZhaoyuan1/Source/MeshBuilder.h
LiZhaoyuan1/Source/MeshBuilder.cpp