My Application: SceneGalaxy Class Reference
SceneGalaxy Class Reference
Defines the scene Galaxy and its methods.
#include <SceneGalaxy.h>
Public Member Functions
SceneGalaxy ()
SceneGalaxy constructor.
~SceneGalaxy ()
SceneGalaxy destructor.
void skybox ()
virtual void Init ()
Scene Galaxy main initializer function.
virtual void Update (double dt)
SceneGalaxy main update function.
void XWingHealth ()
virtual void Render ()
SceneGalaxy Render function.
virtual void RenderXwing ()
SceneGalaxy RenderXWing function.
virtual void RenderAsteroid ()
SceneGalaxy RenderAsteroid function.
virtual void MovingAsteroid (double dt)
SceneGalaxy MovingAsteroid function.
int getMagnitude (Vector3 A, Vector3 B)
SceneGalaxy getMagnitude function.
virtual void RenderMissile ()
SceneGalaxy RenderMissile function.
void QuestDetail ()
SceneGalaxy QuestDetail function.
bool CheckCollision (Vector3 A, Vector3 B)
SceneGalaxy CheckCollision function.
bool CheckAsteroidStartWave ()
SceneGalaxy CheckAsteroidStartWave function.
bool CheckAsteroidWave1 ()
SceneGalaxy CheckAsteroidWave1 function.
bool CheckAsteroidWave2 ()
SceneGalaxy CheckAsteoidWave2 function.
bool CheckLargeAsteroid ()
SceneGalaxy CheckLargeAsteroid function.
void CutScene (double dt)
SceneGalaxy CutScene function.
virtual void Exit ()
SceneGalaxy Exit function.
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_QUAD, GEO_CUBE, GEO_SPHERE,
GEO_LIGHTBALL, GEO_TEXT, GEO_GALAXYLEFT, GEO_GALAXYRIGHT,
GEO_GALAXYTOP, GEO_GALAXYBOTTOM, GEO_GALAXYFRONT, GEO_GALAXYBACK,
GEO_GALAXYGROUND, GEO_ASTEROID, GEO_XWING, GEO_MISSILE,
GEO_BLACKSCREEN, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF,
U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_NUMLIGHTS, U_COLOR_TEXTURE_ENABLED,
U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR, U_TOTAL
}
Private Member Functions
void renderMesh (Mesh *mesh, bool enableLight)
SceneGalaxy renderMesh function.
void RenderSkybox ()
SceneGalaxy RenderSkybox function.
void RenderText (Mesh *mesh, std::string text, Color color)
SceneGalaxy RenderText function.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
SceneGalaxy RenderTextOnScreen function.
void MunInit ()
void MunRender ()
void GalaxyInit ()
void GalaxyRender ()
void SoraJewelInit ()
void SoraJewelRender ()
Private Attributes
Light light [2]
bool enableLight = false
float LSPEED = 10.f
int fps = 0
float delaymissile = 0
float rotateXWing = 0.f
bool rotateXWing_Limit
bool shootMissile = false
bool QuestDetailShown = false
bool renderAsteroid = true
bool renderAsteroid2 = true
bool renderAsteroid3 = true
bool renderAsteroid4 = true
bool renderAsteroid5 = true
bool renderAsteroid6 = true
bool renderAsteroid7 = true
bool renderAsteroid8 = true
bool renderAsteroid9 = true
bool renderAsteroid10 = true
bool renderAsteroidLarge = true
bool renderXWing = true
bool renderSkybox = true
Vector3 target
Vector3 position
Vector3 XWing = Vector3(0, 495, -10)
Vector3 Asteroid = Vector3(-123, 486, -600)
Vector3 Asteroid2 = Vector3(4, 520, -600)
Vector3 Asteroid3 = Vector3(124, 570, -600)
Vector3 Asteroid4 = Vector3(10, 600, -600)
Vector3 Asteroid5 = Vector3(-153, 467, -600)
Vector3 Asteroid6 = Vector3(40, 470, -600)
Vector3 Asteroid7 = Vector3(-70, 450, -600)
Vector3 Asteroid8 = Vector3(-124, 500, -609)
Vector3 Asteroid9 = Vector3(-40, 600, -723)
Vector3 Asteroid10 = Vector3(67, 578, -600)
Vector3 LAsteroid = Vector3(-2, 700, 600)
Vector3 missilePos = Vector3(0, 0, 0)
Vector3 missileTar = Vector3(0, 0, 0)
Vector3 missileView
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Camera3 camera
float boxX = 0
float boxZ = 0
float camPosX = 0
float camPosY = 0
float camPosz = 0
float camView = 0
MS modelStack
MS viewStack
MS projectionStack
Detailed Description
Defines the scene Galaxy and its methods.
Class SceneGalaxy:
Definition at line 33 of file SceneGalaxy.h.
Member Enumeration Documentation
enum SceneGalaxy::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_QUAD
GEO_CUBE
GEO_SPHERE
GEO_LIGHTBALL
GEO_TEXT
GEO_GALAXYLEFT
GEO_GALAXYRIGHT
GEO_GALAXYTOP
GEO_GALAXYBOTTOM
GEO_GALAXYFRONT
GEO_GALAXYBACK
GEO_GALAXYGROUND
GEO_ASTEROID
GEO_XWING
GEO_MISSILE
GEO_BLACKSCREEN
NUM_GEOMETRY
Definition at line 35 of file SceneGalaxy.h.
enum SceneGalaxy::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 57 of file SceneGalaxy.h.
Constructor & Destructor Documentation
SceneGalaxy::SceneGalaxy ()
SceneGalaxy constructor.
Definition at line 35 of file SceneGalaxy.cpp.
SceneGalaxy::~SceneGalaxy ()
SceneGalaxy destructor.
Definition at line 44 of file SceneGalaxy.cpp.
Member Function Documentation
bool SceneGalaxy::CheckAsteroidStartWave ()
SceneGalaxy CheckAsteroidStartWave function.
Returns
true/false
Definition at line 440 of file SceneGalaxy.cpp.
References renderAsteroid, renderAsteroid2, and renderAsteroid3.
Referenced by CutScene(), and MovingAsteroid().
bool SceneGalaxy::CheckAsteroidWave1 ()
SceneGalaxy CheckAsteroidWave1 function.
Returns
true/false
Definition at line 454 of file SceneGalaxy.cpp.
References renderAsteroid4, renderAsteroid5, and renderAsteroid6.
Referenced by CutScene(), and MovingAsteroid().
bool SceneGalaxy::CheckAsteroidWave2 ()
SceneGalaxy CheckAsteoidWave2 function.
Returns
true/false
Definition at line 468 of file SceneGalaxy.cpp.
References renderAsteroid10, renderAsteroid7, renderAsteroid8, and renderAsteroid9.
Referenced by CutScene(), and MovingAsteroid().
bool SceneGalaxy::CheckCollision (Vector3 A, Vector3 B)
SceneGalaxy CheckCollision function.
Parameters
Vector3 A Vector3 B
Returns
true/false
Definition at line 503 of file SceneGalaxy.cpp.
References Vector3::x, Vector3::y, and Vector3::z.
Referenced by MovingAsteroid().
bool SceneGalaxy::CheckLargeAsteroid ()
SceneGalaxy CheckLargeAsteroid function.
Returns
true/false
Definition at line 482 of file SceneGalaxy.cpp.
References renderAsteroidLarge.
Referenced by CutScene(), and MovingAsteroid().
void SceneGalaxy::CutScene (double dt)
SceneGalaxy CutScene function.
Parameters
delta time
Definition at line 1062 of file SceneGalaxy.cpp.
References camera, CheckAsteroidStartWave(), CheckAsteroidWave1(), CheckAsteroidWave2(), CheckLargeAsteroid(), Gamemode::currentgamestate, Gamemode::getinstance(), Camera3::Init(), and shootMissile.
Referenced by Update().
void SceneGalaxy::Exit () virtual
SceneGalaxy Exit function.
Implements Scene.
Definition at line 1115 of file SceneGalaxy.cpp.
References m_programID, and m_vertexArrayID.
void SceneGalaxy::GalaxyInit () private
void SceneGalaxy::GalaxyRender () private
int SceneGalaxy::getMagnitude (Vector3 A, Vector3 B)
SceneGalaxy getMagnitude function.
Parameters
Vector3 A Vector3 B
Returns
Magnitude
Definition at line 523 of file SceneGalaxy.cpp.
References Vector3::x, Vector3::y, and Vector3::z.
Referenced by MovingAsteroid().
void SceneGalaxy::Init () virtual
Scene Galaxy main initializer function.
Implements Scene.
Definition at line 54 of file SceneGalaxy.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateCube(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_ASTEROID, GEO_AXES, GEO_BLACKSCREEN, GEO_CUBE, GEO_GALAXYBACK, GEO_GALAXYBOTTOM, GEO_GALAXYFRONT, GEO_GALAXYLEFT, GEO_GALAXYRIGHT, GEO_GALAXYTOP, GEO_LIGHTBALL, GEO_MISSILE, GEO_QUAD, GEO_TEXT, GEO_XWING, Missile::init(), Camera3::Init(), Material::kAmbient, Light::kC, Material::kDiffuse, Light::kL, Light::kQ, Material::kShininess, Material::kSpecular, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, Mesh::material, meshList, missile, Light::position, Light::power, projectionStack, Camera3::SceneGalaxy, Camera3::SceneMun, Camera3::SceneSoraJewel, Component::Set(), Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, and U_TEXT_ENABLED.
void SceneGalaxy::MovingAsteroid (double dt) virtual
SceneGalaxy MovingAsteroid function.
Parameters
delta time
Definition at line 243 of file SceneGalaxy.cpp.
References Asteroid, Asteroid10, Asteroid2, Asteroid3, Asteroid4, Asteroid5, Asteroid6, Asteroid7, Asteroid8, Asteroid9, CheckAsteroidStartWave(), CheckAsteroidWave1(), CheckAsteroidWave2(), CheckCollision(), CheckLargeAsteroid(), getMagnitude(), LAsteroid, missilePos, missileTar, missileView, QuestDetailShown, renderAsteroid, renderAsteroid10, renderAsteroid2, renderAsteroid3, renderAsteroid4, renderAsteroid5, renderAsteroid6, renderAsteroid7, renderAsteroid8, renderAsteroid9, renderAsteroidLarge, renderSkybox, renderXWing, and XWing.
Referenced by Update().
void SceneGalaxy::MunInit () private
void SceneGalaxy::MunRender () private
void SceneGalaxy::QuestDetail ()
SceneGalaxy QuestDetail function.
Definition at line 1081 of file SceneGalaxy.cpp.
References GEO_BLACKSCREEN, Application::IsKeyPressed(), MS::LoadIdentity(), MS::LoadMatrix(), meshList, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), QuestDetailShown, renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render().
void SceneGalaxy::Render () virtual
SceneGalaxy Render function.
Implements Scene.
Definition at line 776 of file SceneGalaxy.cpp.
References camera, camPosX, camPosY, camPosz, fps, GEO_LIGHTBALL, GEO_TEXT, light, MS::LoadIdentity(), MS::LookAt(), meshList, modelStack, MS::PopMatrix(), Light::position, Camera::position, position, MS::PushMatrix(), QuestDetail(), RenderAsteroid(), renderMesh(), RenderMissile(), RenderSkybox(), RenderTextOnScreen(), RenderXwing(), MS::Scale(), Mtx44::SetToIdentity(), Mtx44::SetToPerspective(), Camera::target, MS::Translate(), Camera::up, viewStack, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneGalaxy::RenderAsteroid () virtual
SceneGalaxy RenderAsteroid function.
Definition at line 867 of file SceneGalaxy.cpp.
References Asteroid, Asteroid10, Asteroid2, Asteroid3, Asteroid4, Asteroid5, Asteroid6, Asteroid7, Asteroid8, Asteroid9, GEO_ASTEROID, LAsteroid, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderAsteroid, renderAsteroid10, renderAsteroid2, renderAsteroid3, renderAsteroid4, renderAsteroid5, renderAsteroid6, renderAsteroid7, renderAsteroid8, renderAsteroid9, renderAsteroidLarge, renderMesh(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SceneGalaxy::renderMesh (Mesh * mesh, bool enableLight) private
SceneGalaxy renderMesh function.
Parameters
The mesh that is rendering Determine if the OBJ allows light to affect it
Definition at line 635 of file SceneGalaxy.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by QuestDetail(), Render(), RenderAsteroid(), RenderMissile(), RenderSkybox(), and RenderXwing().
void SceneGalaxy::RenderMissile () virtual
SceneGalaxy RenderMissile function.
Definition at line 975 of file SceneGalaxy.cpp.
References camera, Missile::Capacity, GEO_MISSILE, Missile::getPositionOfMissile(), meshList, missile, missilePos, Missile::Missiles, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), Camera3::rotateChar, MS::Scale(), shootMissile, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SceneGalaxy::RenderSkybox () private
SceneGalaxy RenderSkybox function.
Definition at line 998 of file SceneGalaxy.cpp.
References GEO_GALAXYBACK, GEO_GALAXYBOTTOM, GEO_GALAXYFRONT, GEO_GALAXYLEFT, GEO_GALAXYRIGHT, GEO_GALAXYTOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), renderSkybox, MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneGalaxy::RenderText (Mesh * mesh, std::string text, Color color) private
SceneGalaxy RenderText function.
Parameters
The mesh that is rendering The text that is being render Color of the Text
Definition at line 689 of file SceneGalaxy.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SceneGalaxy::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
SceneGalaxy RenderTextOnScreen function.
Parameters
The mesh that is rendering The text that is being render Color of the text Size of the text x Coord of the text z Coord of the text
Definition at line 728 of file SceneGalaxy.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render().
void SceneGalaxy::RenderXwing () virtual
SceneGalaxy RenderXWing function.
Definition at line 846 of file SceneGalaxy.cpp.
References camera, GEO_XWING, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), renderXWing, MS::Rotate(), Camera3::rotateChar, rotateXWing, MS::Scale(), MS::Translate(), Vector3::x, XWing, Vector3::y, and Vector3::z.
Referenced by Render().
void SceneGalaxy::skybox ()
void SceneGalaxy::SoraJewelInit () private
void SceneGalaxy::SoraJewelRender () private
void SceneGalaxy::Update (double dt) virtual
SceneGalaxy main update function.
Parameters
delta time
Implements Scene.
Definition at line 542 of file SceneGalaxy.cpp.
References camera, camPosX, camPosY, camPosz, CutScene(), delaymissile, enableLight, Missile::Firing(), fps, Application::IsKeyPressed(), light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, LSPEED, m_parameters, missile, MovingAsteroid(), Light::position, Camera::position, position, shootMissile, Light::type, U_LIGHT0_TYPE, Missile::update(), Vector3::x, Camera3::XWingCamera(), Vector3::y, Position::z, and Vector3::z.
void SceneGalaxy::XWingHealth ()
Field Documentation
Vector3 SceneGalaxy::Asteroid = Vector3(-123, 486, -600) private
Definition at line 149 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderAsteroid().
Vector3 SceneGalaxy::Asteroid10 = Vector3(67, 578, -600) private
Definition at line 158 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderAsteroid().
Vector3 SceneGalaxy::Asteroid2 = Vector3(4, 520, -600) private
Definition at line 150 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderAsteroid().
Vector3 SceneGalaxy::Asteroid3 = Vector3(124, 570, -600) private
Definition at line 151 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderAsteroid().
Vector3 SceneGalaxy::Asteroid4 = Vector3(10, 600, -600) private
Definition at line 152 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderAsteroid().
Vector3 SceneGalaxy::Asteroid5 = Vector3(-153, 467, -600) private
Definition at line 153 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderAsteroid().
Vector3 SceneGalaxy::Asteroid6 = Vector3(40, 470, -600) private
Definition at line 154 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderAsteroid().
Vector3 SceneGalaxy::Asteroid7 = Vector3(-70, 450, -600) private
Definition at line 155 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderAsteroid().
Vector3 SceneGalaxy::Asteroid8 = Vector3(-124, 500, -609) private
Definition at line 156 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderAsteroid().
Vector3 SceneGalaxy::Asteroid9 = Vector3(-40, 600, -723) private
Definition at line 157 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderAsteroid().
float SceneGalaxy::boxX = 0 private
Definition at line 181 of file SceneGalaxy.h.
float SceneGalaxy::boxZ = 0 private
Definition at line 182 of file SceneGalaxy.h.
Camera3 SceneGalaxy::camera private
Definition at line 179 of file SceneGalaxy.h.
Referenced by CutScene(), Init(), Render(), RenderMissile(), RenderXwing(), and Update().
float SceneGalaxy::camPosX = 0 private
Definition at line 183 of file SceneGalaxy.h.
Referenced by Render(), and Update().
float SceneGalaxy::camPosY = 0 private
Definition at line 184 of file SceneGalaxy.h.
Referenced by Render(), and Update().
float SceneGalaxy::camPosz = 0 private
Definition at line 185 of file SceneGalaxy.h.
Referenced by Render(), and Update().
float SceneGalaxy::camView = 0 private
Definition at line 186 of file SceneGalaxy.h.
float SceneGalaxy::delaymissile = 0 private
Definition at line 125 of file SceneGalaxy.h.
Referenced by Update().
bool SceneGalaxy::enableLight = false private
Definition at line 122 of file SceneGalaxy.h.
Referenced by Update().
int SceneGalaxy::fps = 0 private
Definition at line 124 of file SceneGalaxy.h.
Referenced by Render(), and Update().
Vector3 SceneGalaxy::LAsteroid = Vector3(-2, 700, 600) private
Definition at line 159 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderAsteroid().
Light SceneGalaxy::light[2] private
Definition at line 121 of file SceneGalaxy.h.
Referenced by Init(), Render(), and Update().
float SceneGalaxy::LSPEED = 10.f private
Definition at line 123 of file SceneGalaxy.h.
Referenced by Update().
unsigned SceneGalaxy::m_parameters[U_TOTAL] private
Definition at line 177 of file SceneGalaxy.h.
Referenced by Init(), renderMesh(), RenderText(), RenderTextOnScreen(), and Update().
unsigned SceneGalaxy::m_programID private
Definition at line 176 of file SceneGalaxy.h.
Referenced by Exit(), and Init().
unsigned SceneGalaxy::m_vertexArrayID private
Definition at line 173 of file SceneGalaxy.h.
Referenced by Exit(), and Init().
Mesh* SceneGalaxy::meshList[NUM_GEOMETRY] private
Definition at line 174 of file SceneGalaxy.h.
Referenced by Init(), QuestDetail(), Render(), RenderAsteroid(), RenderMissile(), RenderSkybox(), and RenderXwing().
Vector3 SceneGalaxy::missilePos = Vector3(0, 0, 0) private
Definition at line 161 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderMissile().
Vector3 SceneGalaxy::missileTar = Vector3(0, 0, 0) private
Definition at line 162 of file SceneGalaxy.h.
Referenced by MovingAsteroid().
Vector3 SceneGalaxy::missileView private
Definition at line 163 of file SceneGalaxy.h.
Referenced by MovingAsteroid().
MS SceneGalaxy::modelStack private
Definition at line 197 of file SceneGalaxy.h.
Referenced by QuestDetail(), Render(), RenderAsteroid(), renderMesh(), RenderMissile(), RenderSkybox(), RenderText(), RenderTextOnScreen(), and RenderXwing().
Vector3 SceneGalaxy::position private
Definition at line 147 of file SceneGalaxy.h.
Referenced by Render(), and Update().
MS SceneGalaxy::projectionStack private
Definition at line 197 of file SceneGalaxy.h.
Referenced by Init(), QuestDetail(), renderMesh(), RenderText(), and RenderTextOnScreen().
bool SceneGalaxy::QuestDetailShown = false private
Definition at line 131 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and QuestDetail().
bool SceneGalaxy::renderAsteroid = true private
Definition at line 132 of file SceneGalaxy.h.
Referenced by CheckAsteroidStartWave(), MovingAsteroid(), and RenderAsteroid().
bool SceneGalaxy::renderAsteroid10 = true private
Definition at line 141 of file SceneGalaxy.h.
Referenced by CheckAsteroidWave2(), MovingAsteroid(), and RenderAsteroid().
bool SceneGalaxy::renderAsteroid2 = true private
Definition at line 133 of file SceneGalaxy.h.
Referenced by CheckAsteroidStartWave(), MovingAsteroid(), and RenderAsteroid().
bool SceneGalaxy::renderAsteroid3 = true private
Definition at line 134 of file SceneGalaxy.h.
Referenced by CheckAsteroidStartWave(), MovingAsteroid(), and RenderAsteroid().
bool SceneGalaxy::renderAsteroid4 = true private
Definition at line 135 of file SceneGalaxy.h.
Referenced by CheckAsteroidWave1(), MovingAsteroid(), and RenderAsteroid().
bool SceneGalaxy::renderAsteroid5 = true private
Definition at line 136 of file SceneGalaxy.h.
Referenced by CheckAsteroidWave1(), MovingAsteroid(), and RenderAsteroid().
bool SceneGalaxy::renderAsteroid6 = true private
Definition at line 137 of file SceneGalaxy.h.
Referenced by CheckAsteroidWave1(), MovingAsteroid(), and RenderAsteroid().
bool SceneGalaxy::renderAsteroid7 = true private
Definition at line 138 of file SceneGalaxy.h.
Referenced by CheckAsteroidWave2(), MovingAsteroid(), and RenderAsteroid().
bool SceneGalaxy::renderAsteroid8 = true private
Definition at line 139 of file SceneGalaxy.h.
Referenced by CheckAsteroidWave2(), MovingAsteroid(), and RenderAsteroid().
bool SceneGalaxy::renderAsteroid9 = true private
Definition at line 140 of file SceneGalaxy.h.
Referenced by CheckAsteroidWave2(), MovingAsteroid(), and RenderAsteroid().
bool SceneGalaxy::renderAsteroidLarge = true private
Definition at line 142 of file SceneGalaxy.h.
Referenced by CheckLargeAsteroid(), MovingAsteroid(), and RenderAsteroid().
bool SceneGalaxy::renderSkybox = true private
Definition at line 144 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderSkybox().
bool SceneGalaxy::renderXWing = true private
Definition at line 143 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderXwing().
float SceneGalaxy::rotateXWing = 0.f private
Definition at line 127 of file SceneGalaxy.h.
Referenced by RenderXwing().
bool SceneGalaxy::rotateXWing_Limit private
Definition at line 128 of file SceneGalaxy.h.
bool SceneGalaxy::shootMissile = false private
Definition at line 130 of file SceneGalaxy.h.
Referenced by CutScene(), RenderMissile(), and Update().
Vector3 SceneGalaxy::target private
Definition at line 146 of file SceneGalaxy.h.
MS SceneGalaxy::viewStack private
Definition at line 197 of file SceneGalaxy.h.
Referenced by QuestDetail(), Render(), renderMesh(), RenderText(), and RenderTextOnScreen().
Vector3 SceneGalaxy::XWing = Vector3(0, 495, -10) private
Definition at line 148 of file SceneGalaxy.h.
Referenced by MovingAsteroid(), and RenderXwing().
The documentation for this class was generated from the following files:
LiZhaoyuan1/Source/SceneGalaxy.h
LiZhaoyuan1/Source/SceneGalaxy.cpp