My Application: SceneMun Class Reference
SceneMun Class Reference
Defines the scene Mun and its methods.
#include <SceneMun.h>
Public Member Functions
SceneMun ()
constructor for the .cpp file
~SceneMun ()
Destructor for the .cpp file.
void skybox ()
virtual void Init ()
Main initialiser function for SceneMun.
virtual void Update (double dt)
SceneMun main update Function.
virtual void Render ()
SceneMun's main render function.
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_AXES, GEO_QUAD, GEO_CUBE, GEO_SPHERE,
GEO_LIGHTBALL, GEO_TEXT, GEO_MUNLEFT, GEO_MUNRIGHT,
GEO_MUNTOP, GEO_MUNBOTTOM, GEO_MUNFRONT, GEO_MUNBACK,
GEO_MUNGROUND, GEO_HOUSE, GEO_ORE, GEO_PICKAXE,
GEO_CRASHEDPLANE, GEO_PLANE, GEO_PLANE_TAKEOFF, GEO_MUN,
GEO_MINIMAP, GEO_MAINICON, GEO_FEMALEA, GEO_FEMALEB,
GEO_ALIEN, GEO_MALE, GEO_PROTAGANIST, GEO_SNAKE,
GEO_CAVE, GEO_VILLAGER_LEGLEFT, GEO_VILLAGER_LEGRIGHT, GEO_VILLAGER_ARMLEFT,
GEO_VILLAGER_ARMRIGHT, GEO_VILLAGER_BODY, GEO_CRATE, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF,
U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_NUMLIGHTS, U_COLOR_TEXTURE_ENABLED,
U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR, U_TOTAL
}
enum Interactions {
TALKED_QUEST_DUDE = 0, MINER_GET_LETTER, PLAYER_GET_PICKAXE, MINING,
REPAIRING, TALKING_TO_LADY, TALKING_TO_QUEST_DUDE, TALKING_TO_MINER_CASE_1,
TALKING_TO_MINER_CASE_2, MINED, REPAIRED, CAN_INTERACT,
TALKING_TO_SNAKE
}
Private Member Functions
void renderMesh (Mesh *mesh, bool enableLight)
RenderMesh function.
void lighting ()
void lighting2 ()
void RenderSkybox ()
Renders the Skybox of the scene.
void interactionWithRobby ()
void interactionWithSnowBalls ()
void RenderText (Mesh *mesh, std::string text, Color color)
Renders text.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
To render the texts on screen.
void Renderpicturetoscreen ()
to render the minimap to screen
void npcRotate ()
Function that allows NPCs to follow your view.
void interactions ()
Function that keeps interactions with NPCs.
void RenderPickaxeOnScreen ()
Function To render the Pickaxe of one of the interactions onto the screen.
void RenderLoadingBarOnScreen ()
Function that renders the loading bar when certain interactions are made.
void RenderOreOnScreen ()
Function that Renders the Ore onto the screen when certain ore is mined interaction occurs.
void RenderTextBoxOnScreen ()
Function that renders the textbox around the Texts.
void RenderLetterOnScreen ()
Function that renders the letter on screen when the interaction of recieving a letter.
void RenderInfomationOnScreen ()
Function that renders some texts when certain interactions are done.
void RenderCalefare ()
Function To render out the workers in the scene, Renders only the body.
void fultoninteraction ()
Function that allows the extraction of NPCs from the map, sending them into the air.
Private Attributes
Light light [2]
bool enableLight = false
float LSPEED = 10.f
int fps = 0
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Camera3 camera
float boxX = 0
float boxZ = 0
int camPosX = 0
int camPosY = 0
int camPosz = 0
int interact = 0
int fultonleft
float timing = 0
bool textWL = false
bool textQD = false
bool textminer1 = false
bool textminer2 = false
bool fultonreceived = false
size_t a = 1
size_t b = 1
size_t c = 1
size_t d = 1
std::stringstream ssWLady
std::stringstream ssQuestDude
std::stringstream ssMiner
std::stringstream ssMiner2
std::stringstream thisisastring
std::string sWLady
std::string sQuestDude
std::string sMiner
std::string sMiner2
std::vector< std::string > TextLady
std::vector< std::string > TextQuestDude
std::vector< std::string > TextMiner
std::vector< std::string > TextMiner2
std::vector< std::string >::iterator Ladypos
std::vector< std::string >::iterator QuestDudepos
std::vector< std::string >::iterator Minerpos
std::vector< std::string >::iterator Minerpos2
Vector3 crashedplaneCoord = Vector3(-36.f,4.9f,-49.f)
Vector3 planecoord = Vector3(-36.f, -2.9f, -35.f)
Vector3 questdudehouseCoord = Vector3(33, -5, 20)
Vector3 worriedladyhouseCoord = Vector3(20, -5, -38)
Vector3 worriedladyCoord = Vector3(2, -4, -38)
Vector3 questdudeCoord = Vector3(33, -4, 3)
Vector3 minerandplusCoord = Vector3(-19, 0, 25)
Vector3 caveCoord = Vector3(-35, -5, 35)
Vector3 oreCoord = Vector3(-42, -2.75f, 35)
Vector3 CalefareACoord = Vector3(26, -0.9f, -21)
Vector3 CalefareBCoord = Vector3(26, -0.9f, -10)
Vector3 CalefareCCoord = Vector3(15, -0.9f, 25)
Vector3 SNAKEcoords = Vector3(47.f, -5.5f, 46.f)
Vector3 TranslateCalefareA
Vector3 TranslateCalefareB
Vector3 TranslateCalefareC
Vector3 tempview
Vector3 viewAtOre
Vector3 viewAtLady
Vector3 viewAtDude
Vector3 viewAtMiner
Vector3 viewAtCrashedPlane
Vector3 viewatSNAKE
Vector3 viewatCalefareA
Vector3 viewatCalefareB
Vector3 viewatCalefareC
float worriedladytempx = 0
float worriedladytempz = 0
float minerandplusx = 0
float minerandplusz = 0
float questdudex = 0
float questdudez = 0
float rotateworriedlady = 0
float rotateminer = 0
float rotatequestdude = 0
float loadingbar = 0.01f
float RadiusFromOre
float RadiusFromLady
float RadiusFromDude
float RadiusFromMiner
float RadiusFromCrashedPlane
float RadiusFromSnake
float RadiusFromCalafareA
float RadiusFromCalafareB
float RadiusFromCalafareC
float rotateAngle = 0
float rotateLimbs = 0
float rotateWhole = 0
float translatingChar = 0
float hoverheight = 0
float rotateplane = 0
float translateplane = 0
bool LadyCaptured = false
bool VillageChiefCaptured = false
bool MinerCaptured = false
bool CalefareACaptured = false
bool CalefareBCaptured = false
bool CalefareCCaptured = false
bool Allcaptured = false
int CaptureLadyCap = 0
int CaptureVChiefCap = 0
int CaptureMinerCap =0
int CalefareACap = 0
int CalefareBCap = 0
int CalefareCCap = 0
MS modelStack
MS viewStack
MS projectionStack
Detailed Description
Defines the scene Mun and its methods.
Class SceneMun:
Definition at line 32 of file SceneMun.h.
Member Enumeration Documentation
enum SceneMun::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_QUAD
GEO_CUBE
GEO_SPHERE
GEO_LIGHTBALL
GEO_TEXT
GEO_MUNLEFT
GEO_MUNRIGHT
GEO_MUNTOP
GEO_MUNBOTTOM
GEO_MUNFRONT
GEO_MUNBACK
GEO_MUNGROUND
GEO_HOUSE
GEO_ORE
GEO_PICKAXE
GEO_CRASHEDPLANE
GEO_PLANE
GEO_PLANE_TAKEOFF
GEO_MUN
GEO_MINIMAP
GEO_MAINICON
GEO_FEMALEA
GEO_FEMALEB
GEO_ALIEN
GEO_MALE
GEO_PROTAGANIST
GEO_SNAKE
GEO_CAVE
GEO_VILLAGER_LEGLEFT
GEO_VILLAGER_LEGRIGHT
GEO_VILLAGER_ARMLEFT
GEO_VILLAGER_ARMRIGHT
GEO_VILLAGER_BODY
GEO_CRATE
NUM_GEOMETRY
Definition at line 35 of file SceneMun.h.
enum SceneMun::Interactions private
Enumerator
TALKED_QUEST_DUDE
MINER_GET_LETTER
PLAYER_GET_PICKAXE
MINING
REPAIRING
TALKING_TO_LADY
TALKING_TO_QUEST_DUDE
TALKING_TO_MINER_CASE_1
TALKING_TO_MINER_CASE_2
MINED
REPAIRED
CAN_INTERACT
TALKING_TO_SNAKE
Definition at line 115 of file SceneMun.h.
enum SceneMun::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 75 of file SceneMun.h.
Constructor & Destructor Documentation
SceneMun::SceneMun ()
constructor for the .cpp file
Definition at line 36 of file SceneMun.cpp.
SceneMun::~SceneMun ()
Destructor for the .cpp file.
Definition at line 45 of file SceneMun.cpp.
Member Function Documentation
void SceneMun::Exit () virtual
Implements Scene.
Definition at line 1349 of file SceneMun.cpp.
References m_programID, and m_vertexArrayID.
void SceneMun::fultoninteraction () private
Function that allows the extraction of NPCs from the map, sending them into the air.
Definition at line 1549 of file SceneMun.cpp.
References Allcaptured, CalefareACaptured, CalefareBCaptured, CalefareCCaptured, fultonreceived, GEO_TEXT, LadyCaptured, meshList, MinerCaptured, RenderTextOnScreen(), thisisastring, and VillageChiefCaptured.
Referenced by Render().
void SceneMun::Init () virtual
Main initialiser function for SceneMun.
Parameters
Implements Scene.
Definition at line 60 of file SceneMun.cpp.
References a, Allcaptured, b, c, CalefareACoord, CalefareBCoord, CalefareCCoord, camera, caveCoord, Light::color, Light::cosCutoff, Light::cosInner, crashedplaneCoord, d, Math::DegreeToRadian(), Light::exponent, fultonleft, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateCube(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_ALIEN, GEO_AXES, GEO_CAVE, GEO_CRASHEDPLANE, GEO_CRATE, GEO_CUBE, GEO_FEMALEA, GEO_HOUSE, GEO_LIGHTBALL, GEO_MAINICON, GEO_MINIMAP, GEO_MUNBACK, GEO_MUNBOTTOM, GEO_MUNFRONT, GEO_MUNGROUND, GEO_MUNLEFT, GEO_MUNRIGHT, GEO_MUNTOP, GEO_ORE, GEO_PICKAXE, GEO_PLANE, GEO_PLANE_TAKEOFF, GEO_QUAD, GEO_SNAKE, GEO_TEXT, GEO_VILLAGER_ARMLEFT, GEO_VILLAGER_ARMRIGHT, GEO_VILLAGER_BODY, GEO_VILLAGER_LEGLEFT, GEO_VILLAGER_LEGRIGHT, hoverheight, Camera3::Init(), interact, Material::kAmbient, Light::kC, Material::kDiffuse, Light::kL, Light::kQ, Material::kShininess, Material::kSpecular, Ladypos, light, Light::LIGHT_DIRECTIONAL, loadingbar, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, Mesh::material, meshList, minerandplusCoord, minerandplusx, minerandplusz, Minerpos, Minerpos2, Camera3::minimapcoords, oreCoord, planecoord, Light::position, Light::power, projectionStack, questdudeCoord, questdudehouseCoord, QuestDudepos, questdudex, questdudez, ReadFromTxt(), rotateAngle, rotateminer, rotateplane, rotatequestdude, rotateworriedlady, Camera3::SceneGalaxy, Camera3::SceneMun, Camera3::SceneSoraJewel, Component::Set(), Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), sMiner, sMiner2, Light::spotDirection, sQuestDude, ssMiner, ssMiner2, ssQuestDude, ssWLady, sWLady, TextLady, TextMiner, textminer1, textminer2, TextMiner2, textQD, TextQuestDude, Mesh::textureID, textWL, thisisastring, translateplane, translatingChar, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, worriedladyCoord, worriedladyhouseCoord, worriedladytempx, worriedladytempz, Vector3::x, and Vector3::y.
void SceneMun::interactions () private
Function that keeps interactions with NPCs.
Definition at line 1393 of file SceneMun.cpp.
References CalefareACaptured, CalefareACoord, CalefareBCaptured, CalefareBCoord, CalefareCCaptured, CalefareCCoord, camera, CAN_INTERACT, crashedplaneCoord, fultonleft, fultonreceived, interact, Application::IsKeyPressed(), LadyCaptured, MINED, MINER_GET_LETTER, minerandplusCoord, MinerCaptured, MINING, oreCoord, PLAYER_GET_PICKAXE, Camera::position, questdudeCoord, RadiusFromCalafareA, RadiusFromCalafareB, RadiusFromCalafareC, RadiusFromCrashedPlane, RadiusFromDude, RadiusFromLady, RadiusFromMiner, RadiusFromOre, RadiusFromSnake, REPAIRED, REPAIRING, SNAKEcoords, TALKED_QUEST_DUDE, TALKING_TO_LADY, TALKING_TO_MINER_CASE_1, TALKING_TO_MINER_CASE_2, TALKING_TO_QUEST_DUDE, TALKING_TO_SNAKE, Camera::target, tempview, textminer1, textminer2, textQD, textWL, TranslateCalefareA, TranslateCalefareB, TranslateCalefareC, viewatCalefareA, viewatCalefareB, viewatCalefareC, viewAtCrashedPlane, viewAtDude, viewAtLady, viewAtMiner, viewAtOre, viewatSNAKE, VillageChiefCaptured, and worriedladyCoord.
Referenced by Update().
void SceneMun::interactionWithRobby () private
void SceneMun::interactionWithSnowBalls () private
void SceneMun::lighting () private
Parameters
Definition at line 796 of file SceneMun.cpp.
References light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, m_parameters, Light::position, Light::spotDirection, MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, viewStack, Position::x, Vector3::x, Position::y, and Position::z.
Referenced by Render().
void SceneMun::lighting2 () private
Parameters
Definition at line 831 of file SceneMun.cpp.
References light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, m_parameters, Light::position, Light::spotDirection, MS::Top(), U_LIGHT1_POSITION, U_LIGHT1_SPOTDIRECTION, viewStack, Position::x, Vector3::x, Position::y, and Position::z.
Referenced by Render().
void SceneMun::npcRotate () private
Function that allows NPCs to follow your view.
Definition at line 1362 of file SceneMun.cpp.
References camera, minerandplusCoord, minerandplusx, minerandplusz, Math::PI, Camera::position, questdudeCoord, questdudex, questdudez, rotateminer, rotatequestdude, rotateworriedlady, worriedladyCoord, worriedladytempx, worriedladytempz, Vector3::x, and Vector3::z.
Referenced by Update().
void SceneMun::Render () virtual
SceneMun's main render function.
Parameters
Implements Scene.
Definition at line 1083 of file SceneMun.cpp.
References Allcaptured, CalefareACoord, CalefareBCoord, CalefareCCoord, camera, caveCoord, crashedplaneCoord, fultoninteraction(), GEO_ALIEN, GEO_CAVE, GEO_CRASHEDPLANE, GEO_FEMALEA, GEO_HOUSE, GEO_LIGHTBALL, GEO_MUNGROUND, GEO_ORE, GEO_PICKAXE, GEO_PLANE_TAKEOFF, GEO_SNAKE, GEO_TEXT, hoverheight, interact, lighting(), lighting2(), MS::LoadIdentity(), MS::LookAt(), meshList, MINED, minerandplusCoord, MINING, modelStack, oreCoord, planecoord, PLAYER_GET_PICKAXE, MS::PopMatrix(), Camera::position, MS::PushMatrix(), questdudeCoord, questdudehouseCoord, RenderCalefare(), RenderInfomationOnScreen(), RenderLetterOnScreen(), RenderLoadingBarOnScreen(), renderMesh(), RenderOreOnScreen(), RenderPickaxeOnScreen(), Renderpicturetoscreen(), RenderSkybox(), RenderTextBoxOnScreen(), RenderTextOnScreen(), REPAIRED, REPAIRING, MS::Rotate(), rotateminer, rotateplane, rotatequestdude, rotateWhole, rotateworriedlady, MS::Scale(), Mtx44::SetToIdentity(), Mtx44::SetToPerspective(), SNAKEcoords, Camera::target, MS::Translate(), translateplane, translatingChar, Camera::up, viewStack, worriedladyCoord, worriedladyhouseCoord, Vector3::x, Vector3::y, and Vector3::z.
void SceneMun::RenderCalefare () private
Function To render out the workers in the scene, Renders only the body.
Definition at line 1978 of file SceneMun.cpp.
References GEO_CRATE, GEO_VILLAGER_ARMLEFT, GEO_VILLAGER_ARMRIGHT, GEO_VILLAGER_BODY, GEO_VILLAGER_LEGLEFT, GEO_VILLAGER_LEGRIGHT, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), rotateLimbs, MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneMun::RenderInfomationOnScreen () private
Function that renders some texts when certain interactions are done.
Definition at line 1895 of file SceneMun.cpp.
References Allcaptured, camPosX, camPosY, camPosz, CAN_INTERACT, fps, fultonreceived, GEO_QUAD, GEO_TEXT, interact, MS::LoadIdentity(), MS::LoadMatrix(), meshList, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RadiusFromCalafareA, RadiusFromCalafareB, RadiusFromCalafareC, renderMesh(), RenderTextOnScreen(), REPAIRED, MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), TALKING_TO_SNAKE, MS::Translate(), and viewStack.
Referenced by Render().
void SceneMun::RenderLetterOnScreen () private
Function that renders the letter on screen when the interaction of recieving a letter.
Definition at line 1862 of file SceneMun.cpp.
References GEO_QUAD, GEO_TEXT, interact, MS::LoadIdentity(), MS::LoadMatrix(), meshList, MINER_GET_LETTER, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), TALKED_QUEST_DUDE, MS::Translate(), and viewStack.
Referenced by Render().
void SceneMun::RenderLoadingBarOnScreen () private
Function that renders the loading bar when certain interactions are made.
Definition at line 1654 of file SceneMun.cpp.
References GEO_CUBE, MS::LoadIdentity(), loadingbar, MS::LoadMatrix(), meshList, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render().
void SceneMun::renderMesh (Mesh * mesh, bool enableLight) private
RenderMesh function.
Parameters
mesh mesh that is rendering
enablelight to determine if light affects the object
Exceptions
Definition at line 869 of file SceneMun.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), RenderCalefare(), RenderInfomationOnScreen(), RenderLetterOnScreen(), RenderLoadingBarOnScreen(), RenderOreOnScreen(), RenderPickaxeOnScreen(), Renderpicturetoscreen(), RenderSkybox(), and RenderTextBoxOnScreen().
void SceneMun::RenderOreOnScreen () private
Function that Renders the Ore onto the screen when certain ore is mined interaction occurs.
Definition at line 1684 of file SceneMun.cpp.
References GEO_ORE, interact, MS::LoadIdentity(), MS::LoadMatrix(), meshList, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), REPAIRED, REPAIRING, MS::Rotate(), rotateAngle, MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render().
void SceneMun::RenderPickaxeOnScreen () private
Function To render the Pickaxe of one of the interactions onto the screen.
Definition at line 1598 of file SceneMun.cpp.
References GEO_PICKAXE, Application::IsKeyPressed(), MS::LoadIdentity(), MS::LoadMatrix(), meshList, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), rotateAngle, MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render().
void SceneMun::Renderpicturetoscreen () private
to render the minimap to screen
Parameters
Definition at line 1032 of file SceneMun.cpp.
References camera, GEO_MAINICON, GEO_MINIMAP, MS::LoadIdentity(), MS::LoadMatrix(), meshList, Camera3::minimapcoords, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), viewStack, Vector3::x, and Vector3::y.
Referenced by Render().
void SceneMun::RenderSkybox () private
Renders the Skybox of the scene.
Definition at line 1297 of file SceneMun.cpp.
References GEO_MUNBACK, GEO_MUNBOTTOM, GEO_MUNFRONT, GEO_MUNLEFT, GEO_MUNRIGHT, GEO_MUNTOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), renderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneMun::RenderText (Mesh * mesh, std::string text, Color color) private
Renders text.
Parameters
mesh the mesh that is rendering
text the text that should be rendered
color the color of the text
Exceptions
Definition at line 931 of file SceneMun.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SceneMun::RenderTextBoxOnScreen () private
Function that renders the textbox around the Texts.
Definition at line 1737 of file SceneMun.cpp.
References GEO_QUAD, GEO_TEXT, interact, MS::LoadIdentity(), MS::LoadMatrix(), meshList, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), renderMesh(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), ssMiner, ssMiner2, ssQuestDude, ssWLady, TALKING_TO_LADY, TALKING_TO_MINER_CASE_1, TALKING_TO_MINER_CASE_2, TALKING_TO_QUEST_DUDE, TALKING_TO_SNAKE, MS::Translate(), and viewStack.
Referenced by Render().
void SceneMun::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
To render the texts on screen.
Parameters
mesh the mesh that is rendered
text the text that should be rendered
color the color of the text
Exceptions
Definition at line 977 of file SceneMun.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by fultoninteraction(), Render(), RenderInfomationOnScreen(), RenderLetterOnScreen(), and RenderTextBoxOnScreen().
void SceneMun::skybox ()
void SceneMun::Update (double dt) virtual
SceneMun main update Function.
Parameters
Implements Scene.
Definition at line 418 of file SceneMun.cpp.
References a, Allcaptured, b, c, CalefareACap, CalefareACaptured, CalefareACoord, CalefareBCap, CalefareBCaptured, CalefareBCoord, CalefareCCap, CalefareCCaptured, CalefareCCoord, camera, camPosX, camPosY, camPosz, CaptureLadyCap, CaptureMinerCap, CaptureVChiefCap, Gamemode::currentgamestate, d, fps, fultonleft, Gamemode::getinstance(), hoverheight, Camera3::Init(), interact, interactions(), Application::IsKeyPressed(), LadyCaptured, Ladypos, loadingbar, MINED, minerandplusCoord, MinerCaptured, Minerpos, Minerpos2, MINING, npcRotate(), Camera::position, questdudeCoord, QuestDudepos, REPAIRED, REPAIRING, rotateAngle, rotateLimbs, rotateplane, rotateWhole, sMiner, sMiner2, sQuestDude, ssMiner, ssMiner2, ssQuestDude, ssWLady, sWLady, TALKING_TO_LADY, TALKING_TO_MINER_CASE_1, TALKING_TO_MINER_CASE_2, TALKING_TO_QUEST_DUDE, Camera::target, TextLady, TextMiner, textminer1, textminer2, TextMiner2, textQD, TextQuestDude, textWL, thisisastring, timing, TranslateCalefareA, TranslateCalefareB, TranslateCalefareC, translateplane, translatingChar, Camera3::Update(), VillageChiefCaptured, worriedladyCoord, Vector3::x, Vector3::y, and Vector3::z.
Field Documentation
size_t SceneMun::a = 1 private
Definition at line 195 of file SceneMun.h.
Referenced by Init(), and Update().
bool SceneMun::Allcaptured = false private
Definition at line 282 of file SceneMun.h.
Referenced by fultoninteraction(), Init(), Render(), RenderInfomationOnScreen(), and Update().
size_t SceneMun::b = 1 private
Definition at line 196 of file SceneMun.h.
Referenced by Init(), and Update().
float SceneMun::boxX = 0 private
Definition at line 177 of file SceneMun.h.
float SceneMun::boxZ = 0 private
Definition at line 178 of file SceneMun.h.
size_t SceneMun::c = 1 private
Definition at line 197 of file SceneMun.h.
Referenced by Init(), and Update().
int SceneMun::CalefareACap = 0 private
Definition at line 284 of file SceneMun.h.
Referenced by Update().
bool SceneMun::CalefareACaptured = false private
Definition at line 281 of file SceneMun.h.
Referenced by fultoninteraction(), interactions(), and Update().
Vector3 SceneMun::CalefareACoord = Vector3(26, -0.9f, -21) private
Definition at line 231 of file SceneMun.h.
Referenced by Init(), interactions(), Render(), and Update().
int SceneMun::CalefareBCap = 0 private
Definition at line 284 of file SceneMun.h.
Referenced by Update().
bool SceneMun::CalefareBCaptured = false private
Definition at line 281 of file SceneMun.h.
Referenced by fultoninteraction(), interactions(), and Update().
Vector3 SceneMun::CalefareBCoord = Vector3(26, -0.9f, -10) private
Definition at line 232 of file SceneMun.h.
Referenced by Init(), interactions(), Render(), and Update().
int SceneMun::CalefareCCap = 0 private
Definition at line 284 of file SceneMun.h.
Referenced by Update().
bool SceneMun::CalefareCCaptured = false private
Definition at line 281 of file SceneMun.h.
Referenced by fultoninteraction(), interactions(), and Update().
Vector3 SceneMun::CalefareCCoord = Vector3(15, -0.9f, 25) private
Definition at line 233 of file SceneMun.h.
Referenced by Init(), interactions(), Render(), and Update().
Camera3 SceneMun::camera private
Definition at line 175 of file SceneMun.h.
Referenced by Init(), interactions(), npcRotate(), Render(), Renderpicturetoscreen(), and Update().
int SceneMun::camPosX = 0 private
Definition at line 179 of file SceneMun.h.
Referenced by RenderInfomationOnScreen(), and Update().
int SceneMun::camPosY = 0 private
Definition at line 180 of file SceneMun.h.
Referenced by RenderInfomationOnScreen(), and Update().
int SceneMun::camPosz = 0 private
Definition at line 181 of file SceneMun.h.
Referenced by RenderInfomationOnScreen(), and Update().
int SceneMun::CaptureLadyCap = 0 private
Definition at line 283 of file SceneMun.h.
Referenced by Update().
int SceneMun::CaptureMinerCap =0 private
Definition at line 283 of file SceneMun.h.
Referenced by Update().
int SceneMun::CaptureVChiefCap = 0 private
Definition at line 283 of file SceneMun.h.
Referenced by Update().
Vector3 SceneMun::caveCoord = Vector3(-35, -5, 35) private
Definition at line 229 of file SceneMun.h.
Referenced by Init(), and Render().
Vector3 SceneMun::crashedplaneCoord = Vector3(-36.f,4.9f,-49.f) private
Definition at line 222 of file SceneMun.h.
Referenced by Init(), interactions(), and Render().
size_t SceneMun::d = 1 private
Definition at line 198 of file SceneMun.h.
Referenced by Init(), and Update().
bool SceneMun::enableLight = false private
Definition at line 146 of file SceneMun.h.
int SceneMun::fps = 0 private
Definition at line 148 of file SceneMun.h.
Referenced by RenderInfomationOnScreen(), and Update().
int SceneMun::fultonleft private
Definition at line 185 of file SceneMun.h.
Referenced by Init(), interactions(), and Update().
bool SceneMun::fultonreceived = false private
Definition at line 193 of file SceneMun.h.
Referenced by fultoninteraction(), interactions(), and RenderInfomationOnScreen().
float SceneMun::hoverheight = 0 private
Definition at line 276 of file SceneMun.h.
Referenced by Init(), Render(), and Update().
int SceneMun::interact = 0 private
Definition at line 183 of file SceneMun.h.
Referenced by Init(), interactions(), Render(), RenderInfomationOnScreen(), RenderLetterOnScreen(), RenderOreOnScreen(), RenderTextBoxOnScreen(), and Update().
bool SceneMun::LadyCaptured = false private
Definition at line 280 of file SceneMun.h.
Referenced by fultoninteraction(), interactions(), and Update().
std::vector<std::string>::iterator SceneMun::Ladypos private
Definition at line 216 of file SceneMun.h.
Referenced by Init(), and Update().
Light SceneMun::light[2] private
Definition at line 145 of file SceneMun.h.
Referenced by Init(), lighting(), and lighting2().
float SceneMun::loadingbar = 0.01f private
Definition at line 261 of file SceneMun.h.
Referenced by Init(), RenderLoadingBarOnScreen(), and Update().
float SceneMun::LSPEED = 10.f private
Definition at line 147 of file SceneMun.h.
unsigned SceneMun::m_parameters[U_TOTAL] private
Definition at line 173 of file SceneMun.h.
Referenced by Init(), lighting(), lighting2(), renderMesh(), RenderText(), and RenderTextOnScreen().
unsigned SceneMun::m_programID private
Definition at line 172 of file SceneMun.h.
Referenced by Exit(), and Init().
unsigned SceneMun::m_vertexArrayID private
Definition at line 169 of file SceneMun.h.
Referenced by Exit(), and Init().
Mesh* SceneMun::meshList[NUM_GEOMETRY] private
Definition at line 170 of file SceneMun.h.
Referenced by fultoninteraction(), Init(), Render(), RenderCalefare(), RenderInfomationOnScreen(), RenderLetterOnScreen(), RenderLoadingBarOnScreen(), RenderOreOnScreen(), RenderPickaxeOnScreen(), Renderpicturetoscreen(), RenderSkybox(), and RenderTextBoxOnScreen().
Vector3 SceneMun::minerandplusCoord = Vector3(-19, 0, 25) private
Definition at line 228 of file SceneMun.h.
Referenced by Init(), interactions(), npcRotate(), Render(), and Update().
float SceneMun::minerandplusx = 0 private
Definition at line 251 of file SceneMun.h.
Referenced by Init(), and npcRotate().
float SceneMun::minerandplusz = 0 private
Definition at line 252 of file SceneMun.h.
Referenced by Init(), and npcRotate().
bool SceneMun::MinerCaptured = false private
Definition at line 280 of file SceneMun.h.
Referenced by fultoninteraction(), interactions(), and Update().
std::vector<std::string>::iterator SceneMun::Minerpos private
Definition at line 218 of file SceneMun.h.
Referenced by Init(), and Update().
std::vector<std::string>::iterator SceneMun::Minerpos2 private
Definition at line 219 of file SceneMun.h.
Referenced by Init(), and Update().
MS SceneMun::modelStack private
Definition at line 287 of file SceneMun.h.
Referenced by Render(), RenderCalefare(), RenderInfomationOnScreen(), RenderLetterOnScreen(), RenderLoadingBarOnScreen(), renderMesh(), RenderOreOnScreen(), RenderPickaxeOnScreen(), Renderpicturetoscreen(), RenderSkybox(), RenderText(), RenderTextBoxOnScreen(), and RenderTextOnScreen().
Vector3 SceneMun::oreCoord = Vector3(-42, -2.75f, 35) private
Definition at line 230 of file SceneMun.h.
Referenced by Init(), interactions(), and Render().
Vector3 SceneMun::planecoord = Vector3(-36.f, -2.9f, -35.f) private
Definition at line 223 of file SceneMun.h.
Referenced by Init(), and Render().
MS SceneMun::projectionStack private
Definition at line 287 of file SceneMun.h.
Referenced by Init(), RenderInfomationOnScreen(), RenderLetterOnScreen(), RenderLoadingBarOnScreen(), renderMesh(), RenderOreOnScreen(), RenderPickaxeOnScreen(), Renderpicturetoscreen(), RenderText(), RenderTextBoxOnScreen(), and RenderTextOnScreen().
Vector3 SceneMun::questdudeCoord = Vector3(33, -4, 3) private
Definition at line 227 of file SceneMun.h.
Referenced by Init(), interactions(), npcRotate(), Render(), and Update().
Vector3 SceneMun::questdudehouseCoord = Vector3(33, -5, 20) private
Definition at line 224 of file SceneMun.h.
Referenced by Init(), and Render().
std::vector<std::string>::iterator SceneMun::QuestDudepos private
Definition at line 217 of file SceneMun.h.
Referenced by Init(), and Update().
float SceneMun::questdudex = 0 private
Definition at line 254 of file SceneMun.h.
Referenced by Init(), and npcRotate().
float SceneMun::questdudez = 0 private
Definition at line 255 of file SceneMun.h.
Referenced by Init(), and npcRotate().
float SceneMun::RadiusFromCalafareA private
Definition at line 269 of file SceneMun.h.
Referenced by interactions(), and RenderInfomationOnScreen().
float SceneMun::RadiusFromCalafareB private
Definition at line 270 of file SceneMun.h.
Referenced by interactions(), and RenderInfomationOnScreen().
float SceneMun::RadiusFromCalafareC private
Definition at line 271 of file SceneMun.h.
Referenced by interactions(), and RenderInfomationOnScreen().
float SceneMun::RadiusFromCrashedPlane private
Definition at line 267 of file SceneMun.h.
Referenced by interactions().
float SceneMun::RadiusFromDude private
Definition at line 265 of file SceneMun.h.
Referenced by interactions().
float SceneMun::RadiusFromLady private
Definition at line 264 of file SceneMun.h.
Referenced by interactions().
float SceneMun::RadiusFromMiner private
Definition at line 266 of file SceneMun.h.
Referenced by interactions().
float SceneMun::RadiusFromOre private
Definition at line 263 of file SceneMun.h.
Referenced by interactions().
float SceneMun::RadiusFromSnake private
Definition at line 268 of file SceneMun.h.
Referenced by interactions().
float SceneMun::rotateAngle = 0 private
Definition at line 272 of file SceneMun.h.
Referenced by Init(), RenderOreOnScreen(), RenderPickaxeOnScreen(), and Update().
float SceneMun::rotateLimbs = 0 private
Definition at line 273 of file SceneMun.h.
Referenced by RenderCalefare(), and Update().
float SceneMun::rotateminer = 0 private
Definition at line 258 of file SceneMun.h.
Referenced by Init(), npcRotate(), and Render().
float SceneMun::rotateplane = 0 private
Definition at line 277 of file SceneMun.h.
Referenced by Init(), Render(), and Update().
float SceneMun::rotatequestdude = 0 private
Definition at line 259 of file SceneMun.h.
Referenced by Init(), npcRotate(), and Render().
float SceneMun::rotateWhole = 0 private
Definition at line 274 of file SceneMun.h.
Referenced by Render(), and Update().
float SceneMun::rotateworriedlady = 0 private
Definition at line 257 of file SceneMun.h.
Referenced by Init(), npcRotate(), and Render().
std::string SceneMun::sMiner private
Definition at line 208 of file SceneMun.h.
Referenced by Init(), and Update().
std::string SceneMun::sMiner2 private
Definition at line 209 of file SceneMun.h.
Referenced by Init(), and Update().
Vector3 SceneMun::SNAKEcoords = Vector3(47.f, -5.5f, 46.f) private
Definition at line 234 of file SceneMun.h.
Referenced by interactions(), and Render().
std::string SceneMun::sQuestDude private
Definition at line 207 of file SceneMun.h.
Referenced by Init(), and Update().
std::stringstream SceneMun::ssMiner private
Definition at line 202 of file SceneMun.h.
Referenced by Init(), RenderTextBoxOnScreen(), and Update().
std::stringstream SceneMun::ssMiner2 private
Definition at line 203 of file SceneMun.h.
Referenced by Init(), RenderTextBoxOnScreen(), and Update().
std::stringstream SceneMun::ssQuestDude private
Definition at line 201 of file SceneMun.h.
Referenced by Init(), RenderTextBoxOnScreen(), and Update().
std::stringstream SceneMun::ssWLady private
Definition at line 200 of file SceneMun.h.
Referenced by Init(), RenderTextBoxOnScreen(), and Update().
std::string SceneMun::sWLady private
Definition at line 206 of file SceneMun.h.
Referenced by Init(), and Update().
Vector3 SceneMun::tempview private
Definition at line 238 of file SceneMun.h.
Referenced by interactions().
std::vector<std::string> SceneMun::TextLady private
Definition at line 211 of file SceneMun.h.
Referenced by Init(), and Update().
std::vector<std::string> SceneMun::TextMiner private
Definition at line 213 of file SceneMun.h.
Referenced by Init(), and Update().
bool SceneMun::textminer1 = false private
Definition at line 191 of file SceneMun.h.
Referenced by Init(), interactions(), and Update().
bool SceneMun::textminer2 = false private
Definition at line 192 of file SceneMun.h.
Referenced by Init(), interactions(), and Update().
std::vector<std::string> SceneMun::TextMiner2 private
Definition at line 214 of file SceneMun.h.
Referenced by Init(), and Update().
bool SceneMun::textQD = false private
Definition at line 190 of file SceneMun.h.
Referenced by Init(), interactions(), and Update().
std::vector<std::string> SceneMun::TextQuestDude private
Definition at line 212 of file SceneMun.h.
Referenced by Init(), and Update().
bool SceneMun::textWL = false private
Definition at line 189 of file SceneMun.h.
Referenced by Init(), interactions(), and Update().
std::stringstream SceneMun::thisisastring private
Definition at line 204 of file SceneMun.h.
Referenced by fultoninteraction(), Init(), and Update().
float SceneMun::timing = 0 private
Definition at line 187 of file SceneMun.h.
Referenced by Update().
Vector3 SceneMun::TranslateCalefareA private
Definition at line 235 of file SceneMun.h.
Referenced by interactions(), and Update().
Vector3 SceneMun::TranslateCalefareB private
Definition at line 236 of file SceneMun.h.
Referenced by interactions(), and Update().
Vector3 SceneMun::TranslateCalefareC private
Definition at line 237 of file SceneMun.h.
Referenced by interactions(), and Update().
float SceneMun::translateplane = 0 private
Definition at line 278 of file SceneMun.h.
Referenced by Init(), Render(), and Update().
float SceneMun::translatingChar = 0 private
Definition at line 275 of file SceneMun.h.
Referenced by Init(), Render(), and Update().
Vector3 SceneMun::viewatCalefareA private
Definition at line 245 of file SceneMun.h.
Referenced by interactions().
Vector3 SceneMun::viewatCalefareB private
Definition at line 246 of file SceneMun.h.
Referenced by interactions().
Vector3 SceneMun::viewatCalefareC private
Definition at line 247 of file SceneMun.h.
Referenced by interactions().
Vector3 SceneMun::viewAtCrashedPlane private
Definition at line 243 of file SceneMun.h.
Referenced by interactions().
Vector3 SceneMun::viewAtDude private
Definition at line 241 of file SceneMun.h.
Referenced by interactions().
Vector3 SceneMun::viewAtLady private
Definition at line 240 of file SceneMun.h.
Referenced by interactions().
Vector3 SceneMun::viewAtMiner private
Definition at line 242 of file SceneMun.h.
Referenced by interactions().
Vector3 SceneMun::viewAtOre private
Definition at line 239 of file SceneMun.h.
Referenced by interactions().
Vector3 SceneMun::viewatSNAKE private
Definition at line 244 of file SceneMun.h.
Referenced by interactions().
MS SceneMun::viewStack private
Definition at line 287 of file SceneMun.h.
Referenced by lighting(), lighting2(), Render(), RenderInfomationOnScreen(), RenderLetterOnScreen(), RenderLoadingBarOnScreen(), renderMesh(), RenderOreOnScreen(), RenderPickaxeOnScreen(), Renderpicturetoscreen(), RenderText(), RenderTextBoxOnScreen(), and RenderTextOnScreen().
bool SceneMun::VillageChiefCaptured = false private
Definition at line 280 of file SceneMun.h.
Referenced by fultoninteraction(), interactions(), and Update().
Vector3 SceneMun::worriedladyCoord = Vector3(2, -4, -38) private
Definition at line 226 of file SceneMun.h.
Referenced by Init(), interactions(), npcRotate(), Render(), and Update().
Vector3 SceneMun::worriedladyhouseCoord = Vector3(20, -5, -38) private
Definition at line 225 of file SceneMun.h.
Referenced by Init(), and Render().
float SceneMun::worriedladytempx = 0 private
Definition at line 248 of file SceneMun.h.
Referenced by Init(), and npcRotate().
float SceneMun::worriedladytempz = 0 private
Definition at line 249 of file SceneMun.h.
Referenced by Init(), and npcRotate().
The documentation for this class was generated from the following files:
LiZhaoyuan1/Source/SceneMun.h
LiZhaoyuan1/Source/SceneMun.cpp