My Application: LiZhaoyuan1/Source/MeshBuilder.cpp File Reference
MeshBuilder.cpp File Reference
#include "MeshBuilder.h"
#include <GL\glew.h>
#include <vector>
#include "MyMath.h"
#include "LoadOBJ.h"
Functions
float circleX (float theta)
float circleZ (float theta)
float sphereX (float phi, float theta)
float sphereY (float phi, float theta)
float sphereZ (float phi, float theta)
float cylinderX (float theta)
float cylinderZ (float theta)
Function Documentation
float circleX (float theta)
Definition at line 229 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCircle(), MeshBuilder::GenerateCone(), and MeshBuilder::GenerateRing().
float circleZ (float theta)
Definition at line 234 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCircle(), MeshBuilder::GenerateCone(), and MeshBuilder::GenerateRing().
float cylinderX (float theta)
Definition at line 376 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCylinder().
float cylinderZ (float theta)
Definition at line 380 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCylinder().
float sphereX (float phi, float theta)
Definition at line 318 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateHemiSphere(), and MeshBuilder::GenerateSphere().
float sphereY (float phi, float theta)
Definition at line 323 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateHemiSphere(), and MeshBuilder::GenerateSphere().
float sphereZ (float phi, float theta)
Definition at line 328 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateHemiSphere(), and MeshBuilder::GenerateSphere().