My Application: LiZhaoyuan1/Source/SceneGalaxy.cpp File Reference
SceneGalaxy.cpp File Reference
SceneGalaxy cpp file, everything needed inside the scene, found here.
#include <sstream>
#include "SceneGalaxy.h"
#include "GL\glew.h"
#include "GLFW\glfw3.h"
#include "shader.hpp"
#include "Mtx44.h"
#include "Application.h"
#include "MeshBuilder.h"
#include "Light.h"
#include "Material.h"
#include "Utility.h"
#include "LoadTGA.h"
Variables
Missile missile (30)
Detailed Description
SceneGalaxy cpp file, everything needed inside the scene, found here.
Author
Li Zhaoyuan, Nathan Chia Shi-Lin, Terence Tan Ming Jie, Muhammad Nurhidayat Bin Suderman
email: lizhaoyuan123.com
Definition in file SceneGalaxy.cpp.
Variable Documentation
Missile missile(30)
Referenced by SceneGalaxy::Init(), SceneGalaxy::RenderMissile(), and SceneGalaxy::Update().